//! Engine-level integration tests against `MockGpu` (no hardware writes) plus
//! parity fixtures generated by running the Python originals (each fixture
//! records the generating command).

use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::Arc;

use crate::gpu::mock::{MockGpu, MockOp};
use crate::gpu::VfPoint;

use super::apply::configure_runtime_spec_policy;
use super::fan::FanConfig;
use super::runtime_spec::{FlattenTarget, LoadedCurve, PlanItem, RuntimeMode};
use super::{run_fan_control_loop, VfPolicyResult};

/// A loop-test publisher pinned to a throwaway state file.
///
/// The runtime loop now writes its state file unconditionally (it is the
/// daemon's live-state channel, not the overlay's on switch), and the default
/// path is the desktop user's cache. Without this, running `cargo test` would
/// overwrite the state file of a daemon actually running on the same machine.
fn loop_test_publisher() -> super::telemetry::OverlayStatePublisher {
    static COUNTER: AtomicUsize = AtomicUsize::new(0);
    let mut publisher = super::telemetry::OverlayStatePublisher::new(
        0,
        false,
        1.0,
        String::new(),
        String::new(),
        String::new(),
        false,
        None,
    );
    let unique = COUNTER.fetch_add(1, Ordering::Relaxed);
    publisher.path = Some(std::env::temp_dir().join(format!(
        "penguin-burner-test-overlay-{}-{unique}.txt",
        std::process::id()
    )));
    publisher
}

fn editable_point(index: u32, freq_khz: i64, voltage_uv: i64, offset_khz: i64) -> VfPoint {
    VfPoint {
        index,
        type_: 0,
        voltage_based: 1,
        freq_khz,
        voltage_uv,
        base_freq_khz: freq_khz - offset_khz,
        base_voltage_uv: voltage_uv,
        current_offset_khz: offset_khz,
    }
}

/// A disabled-fan engine loop still polls telemetry + reapplies the VF curve
/// when the driver drops offsets, and applies no fan writes.
#[test]
fn loop_reapplies_vf_curve_when_driver_resets_offsets() {
    let mut mock = MockGpu::new();
    mock.temperature_c = 55.0;
    mock.power_draw_w = Some(200.0);
    mock.graphics_clock_mhz = Some(2800);
    mock.memory_clock_mhz = Some(12000);
    mock.voltage_uv = Some(900_000);
    mock.vf_available = true;
    // Live point drifted to +0 offset (driver reset) vs expected +120.
    mock.vf_points = vec![editable_point(12, 2_800_000, 900_000, 0)];

    let plan = vec![PlanItem {
        index: 12,
        voltage_mv: 900,
        base_mhz: 2680,
        target_mhz: 2800,
        new_offset_mhz: 120,
    }];
    let vf_policy = VfPolicyResult {
        vf_apply_plan: Some(plan.clone()),
        vf_expected_samples: super::guard::select_expected_vf_samples(&plan, 8),
        active_vf_curve_source: Some("auto-uv-final".into()),
        profile_clock_mhz: Some(2800.0),
        profile_voltage_mv: Some(900.0),
        ..VfPolicyResult::default()
    };

    let stop = Arc::new(AtomicBool::new(false));
    // Fan control disabled → poll_interval only; cooldown = max(poll, 10) but the
    // first reapply has last=0 and loop_started≈0, so it needs > cooldown. Use a
    // tiny poll and run enough iterations past the cooldown via monotonic time.
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0; // no sleep between iterations
    let mut publisher = loop_test_publisher();

    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        false,
        vf_policy,
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(1),
        None,
        &mut None,
    );
    assert!(result.is_ok());
    let ops = mock.recorded();
    // Fan control disabled → never a fan write.
    assert!(!ops
        .iter()
        .any(|op| matches!(op, MockOp::SetAllFansSpeed { .. })));
    // Drift detected + cooldown seeded "long ago" → the whole plan is reapplied
    // (MHz→kHz) on the first iteration, matching Python's absolute-monotonic gate.
    assert!(ops.iter().any(|op| matches!(
        op,
        MockOp::ApplyVfOffsets { offsets } if offsets == &vec![(12, 120_000)]
    )));
}

#[test]
fn runtime_state_file_is_published_with_the_overlay_hud_off() {
    // The GUI reads this file to show what the daemon is *currently* running.
    // An adaptive run reports its initial tier in the immutable job spec
    // forever, so without this the running-profile line stays wrong for the
    // whole session on every host that keeps the in-game HUD switched off.
    let mock = MockGpu::new();
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    let mut publisher = loop_test_publisher();
    // Explicitly the HUD-off case: `enabled` stays false.
    assert!(!publisher.enabled);
    let state_path = publisher.path.clone().expect("test publisher pins a path");
    let _ = std::fs::remove_file(&state_path);

    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        false,
        VfPolicyResult::default(),
        &mut publisher,
        None,
        None,
        None,
        Arc::new(AtomicBool::new(false)),
        Some(1),
        None,
        &mut None,
    );

    assert!(result.is_ok());
    let published = std::fs::read_to_string(&state_path)
        .expect("the runtime loop must publish its state file with the HUD off");
    assert!(published.contains("version=1"));
    assert!(published.contains("gpu_index=0"));
    let _ = std::fs::remove_file(&state_path);
}

/// Build a VF-drifted policy whose applied mem offset is `mem_offset`, so the VF
/// reapply guard fires and the mem-offset guard has a target to check.
fn vf_reapply_policy(mem_offset: i64) -> (Vec<PlanItem>, VfPolicyResult<'static>) {
    let plan = vec![PlanItem {
        index: 12,
        voltage_mv: 900,
        base_mhz: 2680,
        target_mhz: 2800,
        new_offset_mhz: 120,
    }];
    let policy = VfPolicyResult {
        vf_apply_plan: Some(plan.clone()),
        vf_expected_samples: super::guard::select_expected_vf_samples(&plan, 8),
        active_vf_curve_source: Some("auto-uv-final".into()),
        profile_clock_mhz: Some(2800.0),
        profile_voltage_mv: Some(900.0),
        auto_uv_profile_gpu_policy: super::apply::GpuPolicyApplied {
            power_limit_w: None,
            mem_clk_vf_offset_mhz: Some(mem_offset),
        },
        ..VfPolicyResult::default()
    };
    (plan, policy)
}

fn drifted_vf_mock(mem_readback: i32) -> MockGpu {
    let mut mock = MockGpu::new();
    mock.temperature_c = 55.0;
    mock.power_draw_w = Some(200.0);
    mock.graphics_clock_mhz = Some(2800);
    mock.memory_clock_mhz = Some(12000);
    mock.voltage_uv = Some(900_000);
    mock.vf_available = true;
    // Live point drifted to +0 offset (driver reset) vs expected +120 → VF guard fires.
    mock.vf_points = vec![editable_point(12, 2_800_000, 900_000, 0)];
    mock.clock_offsets = crate::gpu::ClockOffsets {
        gpc_clk_vf_offset_mhz: None,
        mem_clk_vf_offset_mhz: Some(mem_readback),
    };
    mock
}

fn run_one_vf_guard_iteration(mock: &MockGpu, policy: VfPolicyResult<'_>) {
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    let mut publisher = loop_test_publisher();
    let stop = Arc::new(AtomicBool::new(false));
    let result = run_fan_control_loop(
        mock,
        0,
        false,
        fan_config,
        false,
        policy,
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(1),
        None,
        &mut None,
    );
    assert!(result.is_ok());
}

/// The mem-offset guard reads the live offset back first and does NOT rewrite it
/// when the readback already matches the applied target — this is what stops the
/// VF/mem guards fighting every cadence (a mem rewrite would wipe the VF table).
#[test]
fn loop_vf_reapply_skips_mem_rewrite_when_readback_matches() {
    let mock = drifted_vf_mock(1500); // mem readback == target 1500 → no rewrite.
    let (_plan, policy) = vf_reapply_policy(1500);
    run_one_vf_guard_iteration(&mock, policy);
    let ops = mock.recorded();
    // The VF curve was reapplied (guard fired)...
    assert!(ops.iter().any(|op| matches!(
        op,
        MockOp::ApplyVfOffsets { offsets } if offsets == &vec![(12, 120_000)]
    )));
    // ...but the matching mem readback means NO mem rewrite was issued.
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::ApplyClockOffsets { .. })),
        "mem offset must NOT be rewritten when the readback already matches: {ops:?}"
    );
}

/// When the mem-offset readback has drifted from the target, the guard DOES
/// rewrite it — and because a mem write wipes the per-point VF table, the mem
/// rewrite must be followed by the VF re-apply in the recorded op sequence.
#[test]
fn loop_vf_reapply_rewrites_mem_then_reapplies_vf_when_readback_drifts() {
    let mock = drifted_vf_mock(0); // mem readback 0 != target 1500 → rewrite.
    let (_plan, policy) = vf_reapply_policy(1500);
    run_one_vf_guard_iteration(&mock, policy);
    let ops = mock.recorded();
    let mem_pos = ops
        .iter()
        .position(|op| {
            matches!(
                op,
                MockOp::ApplyClockOffsets {
                    mem_mhz: Some(1500),
                    ..
                }
            )
        })
        .expect("drifted mem readback must trigger a mem rewrite");
    let vf_pos = ops
        .iter()
        .position(|op| {
            matches!(
                op,
                MockOp::ApplyVfOffsets { offsets } if offsets == &vec![(12, 120_000)]
            )
        })
        .expect("VF curve must be reapplied");
    // Ordered dependency: the mem rewrite (which wipes VF) lands BEFORE the VF
    // re-apply, so the curve survives.
    assert!(
        mem_pos < vf_pos,
        "mem rewrite must precede the VF re-apply, got mem={mem_pos} vf={vf_pos}: {ops:?}"
    );
}

/// The manual fan decision drives a spin-up write and restores fans on stop.
#[test]
fn loop_manual_fan_control_and_restore_on_exit() {
    let mut mock = MockGpu::new();
    mock.fan_count = 2;
    mock.temperature_c = 70.0; // above manual_enable (60), below emergency
    mock.power_draw_w = Some(250.0);
    mock.graphics_clock_mhz = Some(2600);
    mock.reported_fan_speeds = Some(vec![40, 42]);

    // A saved-silent-style fan config (manual 60, restore 45, curve rising).
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    fan_config.manual_enable_temp_c = 60.0;
    fan_config.auto_restore_temp_c = 45.0;
    fan_config.min_fan_speed_pct = 0;
    fan_config.max_fan_speed_pct = 100;
    fan_config.curve = vec![(45.0, 0.0), (60.0, 30.0), (70.0, 50.0), (90.0, 100.0)];

    let mut publisher = loop_test_publisher();
    let stop = Arc::new(AtomicBool::new(false));
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        true,
        VfPolicyResult::default(),
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(2),
        None,
        &mut None,
    );
    assert!(result.is_ok());
    let ops = mock.recorded();
    // Entered manual mode and wrote a fan speed to both fans.
    assert!(ops
        .iter()
        .any(|op| matches!(op, MockOp::SetAllFansSpeed { fan_count: 2, .. })));
    // On loop exit (max_iterations) the cleanup guard restored fans to auto.
    assert!(ops
        .iter()
        .any(|op| matches!(op, MockOp::SetAllFansDefault { fan_count: 2 })));
}

/// A stop request that lands while a backend read is in flight (the wedged-call
/// regime behind `StopOutcome::TimedOut`) must prevent the rest of that
/// iteration's GPU writes: no fan-speed write, no VF re-apply, no mem rewrite —
/// only the cleanup restore.
#[test]
fn loop_stop_during_backend_read_skips_gpu_writes() {
    let mut mock = drifted_vf_mock(0); // drifted VF + mem → both guards WOULD fire
    mock.fan_count = 2;
    mock.temperature_c = 70.0; // above manual_enable (60) → a fan write WOULD fire
    mock.reported_fan_speeds = Some(vec![40, 42]);
    let (_plan, policy) = vf_reapply_policy(1500);

    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    fan_config.manual_enable_temp_c = 60.0;
    fan_config.auto_restore_temp_c = 45.0;
    fan_config.min_fan_speed_pct = 0;
    fan_config.max_fan_speed_pct = 100;
    fan_config.curve = vec![(45.0, 0.0), (60.0, 30.0), (70.0, 50.0), (90.0, 100.0)];

    let stop = Arc::new(AtomicBool::new(false));
    let hook_stop = stop.clone();
    *mock.on_temperature.borrow_mut() =
        Some(Box::new(move || hook_stop.store(true, Ordering::SeqCst)));

    let mut publisher = loop_test_publisher();
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        true,
        policy,
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(5),
        None,
        &mut None,
    );
    assert!(result.is_ok());
    let ops = mock.recorded();
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::SetAllFansSpeed { .. })),
        "no fan write may follow the stop request: {ops:?}"
    );
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::ApplyVfOffsets { .. })),
        "no VF re-apply may follow the stop request: {ops:?}"
    );
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::ApplyClockOffsets { .. })),
        "no mem rewrite may follow the stop request: {ops:?}"
    );
    // The cleanup guard still restores fans to hardware auto.
    assert!(ops
        .iter()
        .any(|op| matches!(op, MockOp::SetAllFansDefault { fan_count: 2 })));
}

/// A stop that lands while the VF-reapply guard's blocking `editable_core_vf_points`
/// read is in flight must bail before the mem/VF writes — those are the writes
/// that would clobber a scan child's curve (mem write wipes the VF table).
#[test]
fn loop_stop_during_vf_read_skips_vf_and_mem_writes() {
    let mock = drifted_vf_mock(0); // drifted VF + mem readback 0 → both guards WOULD fire
    let (_plan, policy) = vf_reapply_policy(1500);

    let stop = Arc::new(AtomicBool::new(false));
    let hook_stop = stop.clone();
    // Fire the stop the moment the VF guard reads the live points (which is
    // AFTER the loop's pre-write checkpoint, so only the in-helper check saves us).
    *mock.on_editable_vf_points.borrow_mut() =
        Some(Box::new(move || hook_stop.store(true, Ordering::SeqCst)));

    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    let mut publisher = loop_test_publisher();
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        false, // fan control disabled → isolate the VF/mem writes
        policy,
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(3),
        None,
        &mut None,
    );
    assert!(result.is_ok());
    let ops = mock.recorded();
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::ApplyVfOffsets { .. })),
        "VF re-apply must not run after the stop landed mid-read: {ops:?}"
    );
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::ApplyClockOffsets { .. })),
        "mem rewrite must not run after the stop landed mid-read: {ops:?}"
    );
}

/// Early engine-setup errors that fire after the clock ceiling was applied (the
/// zero-fans check here) must still release the locked clocks: the controller's
/// `Drop` closes it even though the cleanup guard never took ownership.
#[test]
fn early_setup_error_releases_clock_ceiling() {
    let mut mock = MockGpu::new();
    mock.fan_count = 0; // triggers the zero-fans early `return Err`
    mock.temperature_c = 50.0;
    mock.supported_core_clocks = vec![2400, 2500, 2600, 2640, 2700];

    let mut ceiling = super::ceiling::FlattenedClockCeilingController::new(
        FlattenTarget {
            source: "auto-uv-final".into(),
            lock_clock_mhz: 2640,
            lock_voltage_mv: Some(875),
            end_voltage_mv: Some(875),
            tail_point_count: Some(1),
            ceiling_clock_mhz: None,
            tail_rise_bins: None,
        },
        &mock,
    );
    ceiling.apply().unwrap();
    let vf_policy = VfPolicyResult {
        clock_ceiling_controller: Some(ceiling),
        ..VfPolicyResult::default()
    };

    let mut publisher = loop_test_publisher();
    let stop = Arc::new(AtomicBool::new(false));
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        FanConfig::defaults(),
        true,
        vf_policy,
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(1),
        None,
        &mut None,
    );
    assert_eq!(
        result.unwrap_err(),
        "GPU reports zero controllable fans".to_string()
    );
    // The applied ceiling was released on the early error path.
    assert!(
        mock.recorded()
            .iter()
            .any(|op| matches!(op, MockOp::ResetLockedCoreClocks)),
        "clock ceiling must be released on early setup errors: {:?}",
        mock.recorded()
    );
}

/// Applying an auto-UV-final profile hits the exact op ordering: persistence →
/// memory offset → VF offsets → power limit → locked clock range. The memory
/// offset MUST precede the per-point VF writes because a
/// `nvmlDeviceSetMemClkVfOffset` write WIPES the whole core per-point VF offset
/// table (one-directional; proven 2026-07-07 on driver 610.43.02) — writing it
/// after the curve would erase the fresh curve.
#[test]
fn configure_auto_uv_final_apply_ordering() {
    let mut mock = MockGpu::new();
    mock.vf_available = true;
    mock.supported_core_clocks = vec![2400, 2500, 2600, 2640, 2700];
    mock.mem_offset_range = Some((-2000, 6000));
    mock.power_limits.power_limit_w = Some(320);
    mock.vf_points = vec![editable_point(12, 2_640_000, 875_000, 240_000)];

    let curve = LoadedCurve {
        path: "auto-uv-profile-test-895.json".into(),
        profile_id: "test-895".into(),
        profile_tier: "Balanced".into(),
        profile_tier_key: "balanced".into(),
        plan: vec![PlanItem {
            index: 12,
            voltage_mv: 875,
            base_mhz: 2400,
            target_mhz: 2640,
            new_offset_mhz: 240,
        }],
        lock_clock_mhz: 2640,
        candidate_voltage_mv: 875,
        memory_offset_mhz: Some(1500),
        power_limit_w: Some(320),
        avg_power_w: None,
        base_avg_power_w: None,
        flatten_target: FlattenTarget {
            source: "auto-uv-final".into(),
            lock_clock_mhz: 2640,
            lock_voltage_mv: Some(875),
            end_voltage_mv: Some(875),
            tail_point_count: Some(1),
            ceiling_clock_mhz: None,
            tail_rise_bins: None,
        },
    };

    let mut log = |_: &str| {};
    let result =
        configure_runtime_spec_policy(&mock, true, RuntimeMode::Static, Some(&curve), &mut log)
            .unwrap();

    assert_eq!(
        result.active_vf_curve_source.as_deref(),
        Some("auto-uv-final")
    );
    let ops = mock.recorded();
    let indices: Vec<&MockOp> = ops.iter().collect();
    // persistence first.
    assert!(matches!(indices[0], MockOp::EnablePersistence));
    // Then memory offset, VF offsets, power limit, then locked clock range. The
    // memory write lands BEFORE the VF writes because a mem write wipes the whole
    // per-point VF table (mem-wipes-VF coupling); the reverse order would erase
    // the fresh curve.
    let vf_pos = ops
        .iter()
        .position(|o| matches!(o, MockOp::ApplyVfOffsets { .. }))
        .unwrap();
    let power_pos = ops
        .iter()
        .position(|o| matches!(o, MockOp::ApplyPowerLimit { power_limit_w: 320 }))
        .unwrap();
    let mem_pos = ops
        .iter()
        .position(|o| {
            matches!(
                o,
                MockOp::ApplyClockOffsets {
                    mem_mhz: Some(1500),
                    ..
                }
            )
        })
        .unwrap();
    let lock_pos = ops
        .iter()
        .position(|o| matches!(o, MockOp::ApplyLockedCoreClockRange { .. }))
        .unwrap();
    assert!(mem_pos < vf_pos && vf_pos < power_pos && power_pos < lock_pos);

    let curve = result.auto_uv_final_curve.unwrap();
    assert_eq!(curve.lock_clock_mhz, 2640);
    assert_eq!(curve.candidate_voltage_mv, 875);
    assert_eq!(curve.memory_offset_mhz, Some(1500));
    assert_eq!(curve.power_limit_w, Some(320));
    assert_eq!(curve.plan.len(), 1);
    assert_eq!(curve.plan[0].new_offset_mhz, 240);
    // flatten_target + tier verified against the Python loader on this exact
    // spec-06 example profile (see spec 06 §13):
    //   PENGUIN_BURNER_HOME=<tmp> python3 -c 'from profiles.uv.runtime_auto_uv_profile
    //   import load_auto_uv_final_curve; print(load_auto_uv_final_curve("test-895"))'
    assert_eq!(curve.flatten_target.source, "auto-uv-final");
    assert_eq!(curve.flatten_target.lock_voltage_mv, Some(875));
    assert_eq!(curve.flatten_target.end_voltage_mv, Some(875));
    assert_eq!(curve.flatten_target.tail_point_count, Some(1));
    assert_eq!(curve.flatten_target.ceiling_clock_mhz, None);
    assert_eq!(curve.profile_tier, "Balanced");
    assert_eq!(curve.profile_tier_key, "balanced");
}

/// Live read-only telemetry-formatting smoke against the real GPU (no writes).
/// Compare its output against the Python `format_telemetry`:
///   cargo test -p penguin-burnerd --lib profile::tests::smoke -- --ignored --nocapture
mod smoke {
    use crate::gpu::{GpuBackend, NvmlBackend};

    #[test]
    #[ignore = "requires a live NVIDIA GPU; read-only telemetry formatting"]
    fn live_telemetry_text() {
        let backend = NvmlBackend::open(0).expect("open GPU 0");
        let fan_count = backend.fan_count().expect("fan_count");
        let temp = backend.temperature_c().expect("temperature");
        let power = backend.power_draw_w();
        let text = super::super::format_telemetry(&backend, fan_count, temp, power, "");
        println!("RUST format_telemetry: {text}");
        assert!(text.starts_with("temp="));
        assert!(text.contains("gpu_clock="));
        assert!(text.contains("voltage="));
    }
}

/// Laptop dGPUs commonly return NOT_SUPPORTED for `nvmlDeviceGetNumFans` (the
/// EC owns the fans). With fan control disabled the engine must still start —
/// stock and undervolt-only profiles never touch fans.
#[test]
fn unsupported_fan_count_is_tolerated_when_fan_control_disabled() {
    let mock = MockGpu::new();
    mock.inject_failure(
        "fan_count",
        crate::gpu::GpuError::nvml_with_text("nvmlDeviceGetNumFans", 3, "Not Supported"),
    );

    let mut publisher = loop_test_publisher();
    let stop = Arc::new(AtomicBool::new(false));
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        FanConfig::defaults(),
        false, // fan control disabled → the unsupported fan count must not block
        VfPolicyResult::default(),
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(1),
        None,
        &mut None,
    );
    assert!(
        result.is_ok(),
        "engine must run without fan control when the fan count is unsupported: {result:?}"
    );
}

/// With fan control REQUESTED, an unsupported fan count stays a hard error so
/// the profile falls back instead of silently dropping the fan curve.
#[test]
fn unsupported_fan_count_still_fails_when_fan_control_enabled() {
    let mock = MockGpu::new();
    mock.inject_failure(
        "fan_count",
        crate::gpu::GpuError::nvml_with_text("nvmlDeviceGetNumFans", 3, "Not Supported"),
    );

    let mut publisher = loop_test_publisher();
    let stop = Arc::new(AtomicBool::new(false));
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        FanConfig::defaults(),
        true,
        VfPolicyResult::default(),
        &mut publisher,
        None,
        None,
        None,
        stop,
        Some(1),
        None,
        &mut None,
    );
    assert!(result.is_err());
}

fn resume_mock(limit_w: i64) -> MockGpu {
    MockGpu::with_power_limits(limit_w, limit_w)
}

#[test]
fn resume_recovery_reapplies_drifted_power_limit() {
    // Drifted after a simulated resume: expected 250, driver reports 320.
    let mock = resume_mock(320);
    let reapplied =
        super::run_resume_recovery(&mock, false, Some(250), None).expect("recovery pass");
    assert!(reapplied);
    assert!(mock
        .recorded()
        .iter()
        .any(|op| matches!(op, MockOp::ApplyPowerLimit { power_limit_w: 250 })));

    // Second pass: the limit now reads back as expected — no further writes.
    let ops_before = mock.recorded().len();
    let reapplied =
        super::run_resume_recovery(&mock, false, Some(250), None).expect("recovery pass");
    assert!(!reapplied);
    assert_eq!(mock.recorded().len(), ops_before);

    // Simulated second suspend that resets the limit again: the shadow is
    // cleared, so the drift is visible and reapplied once more.
    mock.clear_applied_power_limit();
    let reapplied =
        super::run_resume_recovery(&mock, false, Some(250), None).expect("recovery pass");
    assert!(reapplied);
}

#[test]
fn resume_recovery_reasserts_persistence_and_ceiling() {
    let mut mock = resume_mock(250);
    mock.supported_core_clocks = vec![2400, 2500, 2600, 2640, 2700];
    let mut ceiling = super::ceiling::FlattenedClockCeilingController::new(
        FlattenTarget {
            source: "auto-uv-final".into(),
            lock_clock_mhz: 2640,
            lock_voltage_mv: Some(875),
            end_voltage_mv: Some(875),
            tail_point_count: Some(1),
            ceiling_clock_mhz: None,
            tail_rise_bins: None,
        },
        &mock,
    );
    ceiling.apply().unwrap();
    let ops_before = mock.recorded().len();

    let reapplied = super::run_resume_recovery(&mock, true, Some(250), Some(&mut ceiling))
        .expect("recovery pass");
    assert!(!reapplied, "limit still matched: read-first must skip it");
    let ops = mock.recorded()[ops_before..].to_vec();
    assert!(
        ops.iter().any(|op| matches!(op, MockOp::EnablePersistence)),
        "persistence must be re-asserted: {ops:?}"
    );
    assert!(
        ops.iter()
            .any(|op| matches!(op, MockOp::ApplyLockedCoreClock { .. })
                || matches!(op, MockOp::ApplyLockedCoreClockRange { .. })),
        "ceiling must be re-locked: {ops:?}"
    );
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::ApplyPowerLimit { .. })),
        "matching power limit must not be rewritten: {ops:?}"
    );
}

#[test]
fn resume_recovery_propagates_power_limit_failure() {
    let mock = resume_mock(320);
    mock.inject_failure(
        "apply_power_limit_w",
        crate::gpu::GpuError::other("injected resume failure", 0),
    );
    let err = super::run_resume_recovery(&mock, false, Some(250), None).expect_err("must fail");
    assert!(err.contains("power limit"), "{err}");
}

#[test]
fn resume_recovery_relocks_ceiling_even_when_power_fails() {
    // The two steps are independent driver state: a failing power-limit
    // reapply must not starve the ceiling re-lock across the retry budget.
    let mut mock = resume_mock(320);
    mock.supported_core_clocks = vec![2400, 2500, 2600, 2640, 2700];
    mock.inject_failure(
        "apply_power_limit_w",
        crate::gpu::GpuError::other("injected resume failure", 0),
    );
    let mut ceiling = super::ceiling::FlattenedClockCeilingController::new(
        FlattenTarget {
            source: "auto-uv-final".into(),
            lock_clock_mhz: 2640,
            lock_voltage_mv: Some(875),
            end_voltage_mv: Some(875),
            tail_point_count: Some(1),
            ceiling_clock_mhz: None,
            tail_rise_bins: None,
        },
        &mock,
    );
    let err = super::run_resume_recovery(&mock, false, Some(250), Some(&mut ceiling))
        .expect_err("power failure must still surface");
    assert!(err.contains("power limit"), "{err}");
    assert!(
        mock.recorded()
            .iter()
            .any(|op| matches!(op, MockOp::ApplyLockedCoreClock { .. })
                || matches!(op, MockOp::ApplyLockedCoreClockRange { .. })),
        "ceiling must be re-locked despite the power failure: {:?}",
        mock.recorded()
    );
}

/// Drive the loop's resume state machine end to end through the clock seam:
/// a fabricated boottime/monotonic gap must quiesce through the grace, then
/// re-verify and reapply the drifted power limit — and nothing before it.
#[test]
fn loop_detects_fabricated_sleep_and_recovers() {
    let mock = MockGpu::with_power_limits(320, 320);
    let policy = VfPolicyResult {
        auto_uv_profile_gpu_policy: super::apply::GpuPolicyApplied {
            power_limit_w: Some(250),
            mem_clk_vf_offset_mhz: None,
        },
        ..VfPolicyResult::default()
    };
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    let mut publisher = loop_test_publisher();
    // setup, tick1 (normal), tick2 (gap: slept 100s), tick3 (grace elapsed).
    let script = std::cell::RefCell::new(std::collections::VecDeque::from(vec![
        (100.0, 100.0),
        (101.0, 101.0),
        (102.0, 202.0),
        (106.0, 206.0),
    ]));
    let mut clocks = || {
        script
            .borrow_mut()
            .pop_front()
            .expect("clock script exhausted")
    };
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        false,
        policy,
        &mut publisher,
        None,
        None,
        None,
        Arc::new(AtomicBool::new(false)),
        Some(3),
        Some(&mut clocks),
        &mut None,
    );
    assert!(result.is_ok(), "{result:?}");
    let ops = mock.recorded();
    assert_eq!(
        ops,
        vec![MockOp::ApplyPowerLimit { power_limit_w: 250 }],
        "exactly one recovery write: the reapplied power limit"
    );
}

/// Exhausting the recovery retry budget must NOT kill the engine: a dying
/// engine would strip fan control and the ceiling while leaving the
/// undervolt applied. Three failing attempts, then the loop keeps running.
#[test]
fn loop_resume_give_up_is_not_fatal() {
    let mock = MockGpu::with_power_limits(320, 320);
    mock.inject_failure(
        "apply_power_limit_w",
        crate::gpu::GpuError::other("post-resume driver refusal", 0),
    );
    let policy = VfPolicyResult {
        auto_uv_profile_gpu_policy: super::apply::GpuPolicyApplied {
            power_limit_w: Some(250),
            mem_clk_vf_offset_mhz: None,
        },
        ..VfPolicyResult::default()
    };
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    let mut publisher = loop_test_publisher();
    // setup; tick1; tick2 detects (deadline 105); tick3 attempt1 + anchor;
    // tick4 attempt2 + anchor; tick5 attempt3 -> give-up; tick6 normal.
    let script = std::cell::RefCell::new(std::collections::VecDeque::from(vec![
        (100.0, 100.0),
        (101.0, 101.0),
        (102.0, 202.0),
        (106.0, 206.0),
        (107.0, 207.0),
        (111.0, 211.0),
        (112.0, 212.0),
        (116.0, 216.0),
        (117.0, 217.0),
    ]));
    let mut clocks = || {
        script
            .borrow_mut()
            .pop_front()
            .expect("clock script exhausted")
    };
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        false,
        policy,
        &mut publisher,
        None,
        None,
        None,
        Arc::new(AtomicBool::new(false)),
        Some(6),
        Some(&mut clocks),
        &mut None,
    );
    assert!(
        result.is_ok(),
        "give-up must be non-fatal, engine keeps running: {result:?}"
    );
    let attempts = mock
        .recorded()
        .iter()
        .filter(|op| matches!(op, MockOp::ApplyPowerLimit { .. }))
        .count();
    assert_eq!(attempts, 3, "exactly the retry budget was spent");
}
