//! Engine-level integration tests against `MockGpu` (no hardware writes) plus
//! parity fixtures generated by running the Python originals (each fixture
//! records the generating command).

use std::sync::atomic::AtomicBool;
use std::sync::Arc;

use crate::gpu::mock::{MockGpu, MockOp};
use crate::gpu::VfPoint;

use super::apply::configure_runtime_vf_curve_policy;
use super::fan::FanConfig;
use super::profile_store::PlanItem;
use super::{run_fan_control_loop, VfPolicyResult};

fn editable_point(index: u32, freq_khz: i64, voltage_uv: i64, offset_khz: i64) -> VfPoint {
    VfPoint {
        index,
        type_: 0,
        voltage_based: 1,
        freq_khz,
        voltage_uv,
        base_freq_khz: freq_khz - offset_khz,
        base_voltage_uv: voltage_uv,
        current_offset_khz: offset_khz,
    }
}

/// A disabled-fan engine loop still polls telemetry + reapplies the VF curve
/// when the driver drops offsets, and applies no fan writes.
#[test]
fn loop_reapplies_vf_curve_when_driver_resets_offsets() {
    let mut mock = MockGpu::new();
    mock.temperature_c = 55.0;
    mock.power_draw_w = Some(200.0);
    mock.graphics_clock_mhz = Some(2800);
    mock.memory_clock_mhz = Some(12000);
    mock.voltage_uv = Some(900_000);
    mock.vf_available = true;
    // Live point drifted to +0 offset (driver reset) vs expected +120.
    mock.vf_points = vec![editable_point(12, 2_800_000, 900_000, 0)];

    let plan = vec![PlanItem {
        index: 12,
        voltage_mv: 900,
        base_mhz: 2680,
        target_mhz: 2800,
        new_offset_mhz: 120,
    }];
    let vf_policy = VfPolicyResult {
        vf_apply_plan: Some(plan.clone()),
        vf_expected_samples: super::guard::select_expected_vf_samples(&plan, 8),
        active_vf_curve_source: Some("auto-uv-final".into()),
        profile_clock_mhz: Some(2800.0),
        profile_voltage_mv: Some(900.0),
        ..VfPolicyResult::default()
    };

    let gpu_cfg = super::config::RuntimeGpuConfig {
        index: 0,
        enable_persistence_mode: false,
    };
    let _ = gpu_cfg; // documents the disabled-fan / no-persistence path

    let stop = Arc::new(AtomicBool::new(false));
    // Fan control disabled → poll_interval only; cooldown = max(poll, 10) but the
    // first reapply has last=0 and loop_started≈0, so it needs > cooldown. Use a
    // tiny poll and run enough iterations past the cooldown via monotonic time.
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0; // no sleep between iterations
    let mut publisher = super::telemetry::OverlayStatePublisher::new(
        0,
        false,
        1.0,
        String::new(),
        String::new(),
        String::new(),
        false,
        None,
        None,
    );

    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        false,
        vf_policy,
        &mut publisher,
        None,
        None,
        stop,
        Some(1),
    );
    assert!(result.is_ok());
    let ops = mock.recorded();
    // Fan control disabled → never a fan write.
    assert!(!ops
        .iter()
        .any(|op| matches!(op, MockOp::SetAllFansSpeed { .. })));
    // Drift detected + cooldown seeded "long ago" → the whole plan is reapplied
    // (MHz→kHz) on the first iteration, matching Python's absolute-monotonic gate.
    assert!(ops.iter().any(|op| matches!(
        op,
        MockOp::ApplyVfOffsets { offsets } if offsets == &vec![(12, 120_000)]
    )));
}

/// Build a VF-drifted policy whose applied mem offset is `mem_offset`, so the VF
/// reapply guard fires and the mem-offset guard has a target to check.
fn vf_reapply_policy(mem_offset: i64) -> (Vec<PlanItem>, VfPolicyResult<'static>) {
    let plan = vec![PlanItem {
        index: 12,
        voltage_mv: 900,
        base_mhz: 2680,
        target_mhz: 2800,
        new_offset_mhz: 120,
    }];
    let policy = VfPolicyResult {
        vf_apply_plan: Some(plan.clone()),
        vf_expected_samples: super::guard::select_expected_vf_samples(&plan, 8),
        active_vf_curve_source: Some("auto-uv-final".into()),
        profile_clock_mhz: Some(2800.0),
        profile_voltage_mv: Some(900.0),
        auto_uv_profile_gpu_policy: super::apply::GpuPolicyApplied {
            power_limit_w: None,
            mem_clk_vf_offset_mhz: Some(mem_offset),
        },
        ..VfPolicyResult::default()
    };
    (plan, policy)
}

fn drifted_vf_mock(mem_readback: i32) -> MockGpu {
    let mut mock = MockGpu::new();
    mock.temperature_c = 55.0;
    mock.power_draw_w = Some(200.0);
    mock.graphics_clock_mhz = Some(2800);
    mock.memory_clock_mhz = Some(12000);
    mock.voltage_uv = Some(900_000);
    mock.vf_available = true;
    // Live point drifted to +0 offset (driver reset) vs expected +120 → VF guard fires.
    mock.vf_points = vec![editable_point(12, 2_800_000, 900_000, 0)];
    mock.clock_offsets = crate::gpu::ClockOffsets {
        gpc_clk_vf_offset_mhz: None,
        mem_clk_vf_offset_mhz: Some(mem_readback),
    };
    mock
}

fn run_one_vf_guard_iteration(mock: &MockGpu, policy: VfPolicyResult<'_>) {
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    let mut publisher = super::telemetry::OverlayStatePublisher::new(
        0,
        false,
        1.0,
        String::new(),
        String::new(),
        String::new(),
        false,
        None,
        None,
    );
    let stop = Arc::new(AtomicBool::new(false));
    let result = run_fan_control_loop(
        mock,
        0,
        false,
        fan_config,
        false,
        policy,
        &mut publisher,
        None,
        None,
        stop,
        Some(1),
    );
    assert!(result.is_ok());
}

/// The mem-offset guard reads the live offset back first and does NOT rewrite it
/// when the readback already matches the applied target — this is what stops the
/// VF/mem guards fighting every cadence (a mem rewrite would wipe the VF table).
#[test]
fn loop_vf_reapply_skips_mem_rewrite_when_readback_matches() {
    let mock = drifted_vf_mock(1500); // mem readback == target 1500 → no rewrite.
    let (_plan, policy) = vf_reapply_policy(1500);
    run_one_vf_guard_iteration(&mock, policy);
    let ops = mock.recorded();
    // The VF curve was reapplied (guard fired)...
    assert!(ops.iter().any(|op| matches!(
        op,
        MockOp::ApplyVfOffsets { offsets } if offsets == &vec![(12, 120_000)]
    )));
    // ...but the matching mem readback means NO mem rewrite was issued.
    assert!(
        !ops.iter()
            .any(|op| matches!(op, MockOp::ApplyClockOffsets { .. })),
        "mem offset must NOT be rewritten when the readback already matches: {ops:?}"
    );
}

/// When the mem-offset readback has drifted from the target, the guard DOES
/// rewrite it — and because a mem write wipes the per-point VF table, the mem
/// rewrite must be followed by the VF re-apply in the recorded op sequence.
#[test]
fn loop_vf_reapply_rewrites_mem_then_reapplies_vf_when_readback_drifts() {
    let mock = drifted_vf_mock(0); // mem readback 0 != target 1500 → rewrite.
    let (_plan, policy) = vf_reapply_policy(1500);
    run_one_vf_guard_iteration(&mock, policy);
    let ops = mock.recorded();
    let mem_pos = ops
        .iter()
        .position(|op| {
            matches!(
                op,
                MockOp::ApplyClockOffsets {
                    mem_mhz: Some(1500),
                    ..
                }
            )
        })
        .expect("drifted mem readback must trigger a mem rewrite");
    let vf_pos = ops
        .iter()
        .position(|op| {
            matches!(
                op,
                MockOp::ApplyVfOffsets { offsets } if offsets == &vec![(12, 120_000)]
            )
        })
        .expect("VF curve must be reapplied");
    // Ordered dependency: the mem rewrite (which wipes VF) lands BEFORE the VF
    // re-apply, so the curve survives.
    assert!(
        mem_pos < vf_pos,
        "mem rewrite must precede the VF re-apply, got mem={mem_pos} vf={vf_pos}: {ops:?}"
    );
}

/// The manual fan decision drives a spin-up write and restores fans on stop.
#[test]
fn loop_manual_fan_control_and_restore_on_exit() {
    let mut mock = MockGpu::new();
    mock.fan_count = 2;
    mock.temperature_c = 70.0; // above manual_enable (60), below emergency
    mock.power_draw_w = Some(250.0);
    mock.graphics_clock_mhz = Some(2600);
    mock.reported_fan_speeds = Some(vec![40, 42]);

    // A saved-silent-style fan config (manual 60, restore 45, curve rising).
    let mut fan_config = FanConfig::defaults();
    fan_config.poll_interval_s = 0.0;
    fan_config.manual_enable_temp_c = 60.0;
    fan_config.auto_restore_temp_c = 45.0;
    fan_config.min_fan_speed_pct = 0;
    fan_config.max_fan_speed_pct = 100;
    fan_config.curve = vec![(45.0, 0.0), (60.0, 30.0), (70.0, 50.0), (90.0, 100.0)];

    let mut publisher = super::telemetry::OverlayStatePublisher::new(
        0,
        false,
        1.0,
        String::new(),
        String::new(),
        String::new(),
        false,
        None,
        None,
    );
    let stop = Arc::new(AtomicBool::new(false));
    let result = run_fan_control_loop(
        &mock,
        0,
        false,
        fan_config,
        true,
        VfPolicyResult::default(),
        &mut publisher,
        None,
        None,
        stop,
        Some(2),
    );
    assert!(result.is_ok());
    let ops = mock.recorded();
    // Entered manual mode and wrote a fan speed to both fans.
    assert!(ops
        .iter()
        .any(|op| matches!(op, MockOp::SetAllFansSpeed { fan_count: 2, .. })));
    // On loop exit (max_iterations) the cleanup guard restored fans to auto.
    assert!(ops
        .iter()
        .any(|op| matches!(op, MockOp::SetAllFansDefault { fan_count: 2 })));
}

/// Applying an auto-UV-final profile hits the exact op ordering: persistence →
/// memory offset → VF offsets → power limit → locked clock range. The memory
/// offset MUST precede the per-point VF writes because a
/// `nvmlDeviceSetMemClkVfOffset` write WIPES the whole core per-point VF offset
/// table (one-directional; proven 2026-07-07 on driver 610.43.02) — writing it
/// after the curve would erase the fresh curve.
#[test]
fn configure_auto_uv_final_apply_ordering() {
    let mut mock = MockGpu::new();
    mock.vf_available = true;
    mock.supported_core_clocks = vec![2400, 2500, 2600, 2640, 2700];
    mock.mem_offset_range = Some((-2000, 6000));
    mock.vf_points = vec![editable_point(12, 2_640_000, 875_000, 240_000)];

    // Write a saved profile to a temp home so the loader reads it.
    let home = std::env::temp_dir().join(format!("pb-prof-{}", std::process::id()));
    let profiles_dir = home.join(".config/PenguinBurner/auto-uv-profiles");
    let _ = std::fs::remove_dir_all(&home);
    std::fs::create_dir_all(&profiles_dir).unwrap();
    let profile = r#"{
  "format_version": 1,
  "final_verified": true,
  "profile_id": "test-895",
  "lock_clock_mhz": 2640,
  "candidate_voltage_mv": 875,
  "power_limit_w": 320,
  "memory_offset_mhz": 1500,
  "points": [
    {"index": 12, "voltage_mv": 875, "base_mhz": 2400, "target_mhz": 2640, "new_offset_mhz": 240}
  ]
}"#;
    std::fs::write(profiles_dir.join("auto-uv-profile-test-895.json"), profile).unwrap();

    let _guard = crate::profile::tests::env_lock();
    std::env::set_var("PENGUIN_BURNER_HOME", &home);

    let mut log = |_: &str| {};
    let result = configure_runtime_vf_curve_policy(&mock, true, "test-895", &mut log).unwrap();
    std::env::remove_var("PENGUIN_BURNER_HOME");

    assert_eq!(
        result.active_vf_curve_source.as_deref(),
        Some("auto-uv-final")
    );
    let ops = mock.recorded();
    let indices: Vec<&MockOp> = ops.iter().collect();
    // persistence first.
    assert!(matches!(indices[0], MockOp::EnablePersistence));
    // Then memory offset, VF offsets, power limit, then locked clock range. The
    // memory write lands BEFORE the VF writes because a mem write wipes the whole
    // per-point VF table (mem-wipes-VF coupling); the reverse order would erase
    // the fresh curve.
    let vf_pos = ops
        .iter()
        .position(|o| matches!(o, MockOp::ApplyVfOffsets { .. }))
        .unwrap();
    let power_pos = ops
        .iter()
        .position(|o| matches!(o, MockOp::ApplyPowerLimit { power_limit_w: 320 }))
        .unwrap();
    let mem_pos = ops
        .iter()
        .position(|o| {
            matches!(
                o,
                MockOp::ApplyClockOffsets {
                    mem_mhz: Some(1500),
                    ..
                }
            )
        })
        .unwrap();
    let lock_pos = ops
        .iter()
        .position(|o| matches!(o, MockOp::ApplyLockedCoreClockRange { .. }))
        .unwrap();
    assert!(mem_pos < vf_pos && vf_pos < power_pos && power_pos < lock_pos);

    let curve = result.auto_uv_final_curve.unwrap();
    assert_eq!(curve.lock_clock_mhz, 2640);
    assert_eq!(curve.candidate_voltage_mv, 875);
    assert_eq!(curve.memory_offset_mhz, Some(1500));
    assert_eq!(curve.power_limit_w, Some(320));
    assert_eq!(curve.plan.len(), 1);
    assert_eq!(curve.plan[0].new_offset_mhz, 240);
    // flatten_target + tier verified against the Python loader on this exact
    // spec-06 example profile (see spec 06 §13):
    //   PENGUIN_BURNER_HOME=<tmp> python3 -c 'from profiles.uv.runtime_auto_uv_profile
    //   import load_auto_uv_final_curve; print(load_auto_uv_final_curve("test-895"))'
    assert_eq!(curve.flatten_target.source, "auto-uv-final");
    assert_eq!(curve.flatten_target.lock_voltage_mv, Some(875));
    assert_eq!(curve.flatten_target.end_voltage_mv, Some(875));
    assert_eq!(curve.flatten_target.tail_point_count, Some(1));
    assert_eq!(curve.flatten_target.ceiling_clock_mhz, None);
    assert_eq!(curve.profile_tier, "Balanced");
    assert_eq!(curve.profile_tier_key, "balanced");
    let _ = std::fs::remove_dir_all(&home);
}

/// Loader legacy aliases — `plan` (not `points`), `mem_clk_vf_offset_mhz` (not
/// `memory_offset_mhz`), and nested `flatten_target.tail_rise_bins` (spec 06 §8.7).
/// Expected values verified against the Python loader:
///   PENGUIN_BURNER_HOME=<tmp> python3 -c 'from profiles.uv.runtime_auto_uv_profile
///   import load_auto_uv_final_curve; print(load_auto_uv_final_curve("latest"))'
/// (canonical `lock_clock_mhz`/`candidate_voltage_mv` are required by the loader —
/// the `clock_mhz`/`voltage_mv` aliases are visibility-only; Python raises without
/// the canonical keys, matching this implementation.)
#[test]
fn loads_legacy_alias_profile() {
    let home = std::env::temp_dir().join(format!("pb-legacy-{}", std::process::id()));
    let profiles_dir = home.join(".config/PenguinBurner/auto-uv-profiles");
    let _ = std::fs::remove_dir_all(&home);
    std::fs::create_dir_all(&profiles_dir).unwrap();
    let legacy = r#"{
  "final_verified": true,
  "candidate_voltage_mv": 900,
  "lock_clock_mhz": 2700,
  "mem_clk_vf_offset_mhz": 1000,
  "flatten_target": {"tail_rise_bins": 5},
  "plan": [
    {"index": 5, "voltage_mv": 900, "base_mhz": 2500, "target_mhz": 2700, "new_offset_mhz": 200}
  ]
}"#;
    std::fs::write(profiles_dir.join("auto-uv-profile-legacy.json"), legacy).unwrap();

    let _guard = env_lock();
    std::env::set_var("PENGUIN_BURNER_HOME", &home);
    let curve = super::profile_store::load_auto_uv_final_curve("latest")
        .unwrap()
        .unwrap();
    std::env::remove_var("PENGUIN_BURNER_HOME");

    assert_eq!(curve.lock_clock_mhz, 2700);
    assert_eq!(curve.candidate_voltage_mv, 900);
    assert_eq!(curve.memory_offset_mhz, Some(1000)); // mem_clk_vf_offset_mhz alias
    assert_eq!(curve.plan[0].new_offset_mhz, 200); // read from `plan`
    assert_eq!(curve.flatten_target.tail_rise_bins, Some(5)); // nested alias
    assert_eq!(curve.flatten_target.end_voltage_mv, Some(900));
    assert_eq!(curve.flatten_target.tail_point_count, Some(1));
    let _ = std::fs::remove_dir_all(&home);
}

// Serialize env-var-mutating tests (env is process-global).
use std::sync::Mutex;
static ENV_LOCK: Mutex<()> = Mutex::new(());
pub(crate) fn env_lock() -> std::sync::MutexGuard<'static, ()> {
    ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner())
}

/// Live read-only telemetry-formatting smoke against the real GPU (no writes).
/// Compare its output against the Python `format_telemetry`:
///   cargo test -p penguin-burnerd --lib profile::tests::smoke -- --ignored --nocapture
mod smoke {
    use crate::gpu::{GpuBackend, NvmlBackend};

    #[test]
    #[ignore = "requires a live NVIDIA GPU; read-only telemetry formatting"]
    fn live_telemetry_text() {
        let backend = NvmlBackend::open(0).expect("open GPU 0");
        let fan_count = backend.fan_count().expect("fan_count");
        let temp = backend.temperature_c().expect("temperature");
        let power = backend.power_draw_w();
        let text = super::super::format_telemetry(&backend, fan_count, temp, power, "");
        println!("RUST format_telemetry: {text}");
        assert!(text.starts_with("temp="));
        assert!(text.contains("gpu_clock="));
        assert!(text.contains("voltage="));
    }
}
