"""Saved undervolt profile storage and lookup.

This package is shared by the CLI, UI, LACT export, and Auto-UV final verification.
"""

from .profile_store import (
    archive_auto_uv_profile,
    auto_uv_profiles_dir,
    delete_auto_uv_profile_paths,
    delete_auto_uv_profiles,
    format_profile_table,
    mark_auto_uv_profile_verification_failed,
    mark_auto_uv_profile_verified,
    profile_display_name,
    profile_summary,
    read_auto_uv_profile_summaries,
    read_auto_uv_profiles,
    resolve_auto_uv_profile,
    wait_for_new_profile,
)
from .profile_tiers import (
    PROFILE_TIER_BALANCED,
    PROFILE_TIER_EFFICIENCY,
    PROFILE_TIER_LABELS,
    PROFILE_TIER_PERFORMANCE,
    PROFILE_TIERS,
    available_adaptive_tiers,
    clear_profile_tier_assignment,
    generated_profile_tier,
    generated_profile_tier_from_runtime_options,
    load_profile_tier_assignments,
    normalize_profile_tier,
    profile_tier_label,
    profile_tier_summary_fields,
    resolve_profile_tier_profiles,
    save_profile_tier_assignment,
)
from .runtime_auto_uv_profile import (
    apply_auto_uv_profile_memory_offset,
    load_auto_uv_final_curve,
    profile_memory_offset_mhz,
)

__all__ = [
    "archive_auto_uv_profile",
    "PROFILE_TIER_BALANCED",
    "PROFILE_TIER_EFFICIENCY",
    "PROFILE_TIER_LABELS",
    "PROFILE_TIER_PERFORMANCE",
    "PROFILE_TIERS",
    "auto_uv_profiles_dir",
    "available_adaptive_tiers",
    "clear_profile_tier_assignment",
    "delete_auto_uv_profile_paths",
    "delete_auto_uv_profiles",
    "format_profile_table",
    "generated_profile_tier",
    "generated_profile_tier_from_runtime_options",
    "load_profile_tier_assignments",
    "mark_auto_uv_profile_verification_failed",
    "mark_auto_uv_profile_verified",
    "profile_display_name",
    "profile_summary",
    "profile_tier_label",
    "profile_tier_summary_fields",
    "read_auto_uv_profile_summaries",
    "read_auto_uv_profiles",
    "resolve_profile_tier_profiles",
    "resolve_auto_uv_profile",
    "save_profile_tier_assignment",
    "normalize_profile_tier",
    "apply_auto_uv_profile_memory_offset",
    "load_auto_uv_final_curve",
    "profile_memory_offset_mhz",
    "wait_for_new_profile",
]
