from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import stat
import sys

from overlay.native_layer import NATIVE_LAYER_LIBRARY
from overlay.native_layer import NATIVE_LAYER_MANIFEST
from overlay.native_layer import native_layer_dirs


APP_ID = "io.github.jpietek.PenguinBurner"
MARKER = "Generated by PenguinBurner Flatpak wrapper installer"
VULKAN_LAYER_ENABLE_ENV = "PENGUIN_BURNER"
VULKAN_LAYER_DISABLE_ENV = "DISABLE_PENGUIN_BURNER_LATENCY_LAYER"
WRAPPERS = (
    "penguin-burner",
    "pburn",
    "penguin-burner-ui",
    "pburn-ui",
    "penguin-burner-cli",
    "pburn-cli",
    "PENGUIN_BURNER",
)


def _default_bin_dir() -> Path:
    override = os.environ.get("PENGUIN_BURNER_FLATPAK_WRAPPER_BIN_DIR")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".local" / "bin"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Install host PATH wrappers for the PenguinBurner Flatpak. "
            "The wrappers forward to flatpak run --command=<name> "
            f"{APP_ID}."
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing non-PenguinBurner wrapper files",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="remove wrappers previously created by this command",
    )
    parser.add_argument(
        "--bin-dir",
        type=Path,
        default=_default_bin_dir(),
        help="install/remove wrappers in DIR (default: ~/.local/bin)",
        metavar="DIR",
    )
    return parser


def _is_managed_wrapper(path: Path) -> bool:
    try:
        return path.is_file() and MARKER in path.read_text(
            encoding="utf-8", errors="replace"
        )
    except OSError:
        return False


def _default_vulkan_manifest_path(home: Path | str | None = None) -> Path:
    home = Path.home() if home is None else Path(home).expanduser()
    return (
        home
        / ".local"
        / "share"
        / "vulkan"
        / "implicit_layer.d"
        / NATIVE_LAYER_MANIFEST
    )


def _stabilize_flatpak_deploy_path(path: Path) -> Path:
    """Rewrite a commit-specific flatpak deploy path to the stable ``active``
    symlink.

    A flatpak deploy path is ``.../<branch>/<commit-hash>/files/...``; the
    Vulkan layer manifest must NOT bake in ``<commit-hash>``, because a
    ``flatpak update`` swaps the active deploy to a new commit and prunes the
    old one — leaving the manifest's library_path dangling and every wrapped
    Vulkan game failing to load the layer. The sibling ``<branch>/active``
    symlink always points at the current deploy, so pinning to it survives
    updates with no wrapper reinstall. Falls back to the original path when the
    ``active`` form does not resolve (e.g. a non-flatpak layout)."""
    parts = list(path.parts)
    try:
        files_index = parts.index("files")
    except ValueError:
        return path
    commit_index = files_index - 1
    if commit_index <= 0:
        return path
    commit = parts[commit_index]
    is_commit = len(commit) == 64 and all(c in "0123456789abcdef" for c in commit)
    if not is_commit:
        return path
    # Structural rewrite only: flatpak always maintains the <branch>/active
    # symlink next to a deploy commit, and the installer runs inside the
    # sandbox where the host active/ path is not visible to stat — so an
    # existence check here would wrongly fall back to the commit path.
    return Path(*parts[:commit_index], "active", *parts[files_index:])


def _host_vulkan_manifest_text(
    native_layer_dir: Path,
    *,
    source_layer_dir: Path | None = None,
) -> str:
    source_layer_dir = native_layer_dir if source_layer_dir is None else source_layer_dir
    manifest = source_layer_dir / NATIVE_LAYER_MANIFEST
    data = json.loads(manifest.read_text(encoding="utf-8"))
    layer = dict(data["layer"])
    layer["library_path"] = str(
        _stabilize_flatpak_deploy_path(native_layer_dir) / NATIVE_LAYER_LIBRARY
    )
    layer["enable_environment"] = {VULKAN_LAYER_ENABLE_ENV: "1"}
    layer["disable_environment"] = {VULKAN_LAYER_DISABLE_ENV: ""}
    data["layer"] = layer
    return json.dumps(data, indent=2) + "\n"


def _flatpak_app_path(flatpak_info_path: Path = Path("/.flatpak-info")) -> Path | None:
    try:
        lines = flatpak_info_path.read_text(
            encoding="utf-8", errors="replace"
        ).splitlines()
    except OSError:
        return None
    for line in lines:
        if line.startswith("app-path="):
            value = line.partition("=")[2].strip()
            if value:
                return Path(value)
    return None


def _native_layer_dirs_from_app_files(app_files: Path) -> list[Path]:
    candidates = [
        path / "overlay" / "native_layer"
        for path in (app_files / "lib").glob("python*/site-packages")
    ]
    return [
        path
        for path in candidates
        if (path / NATIVE_LAYER_MANIFEST).is_file()
        and (path / NATIVE_LAYER_LIBRARY).is_file()
    ]


def _native_layer_dirs_for_host_manifest(
    flatpak_info_path: Path = Path("/.flatpak-info"),
) -> list[tuple[Path, Path]]:
    candidates: list[tuple[Path, Path]] = []
    source_dirs = native_layer_dirs()
    flatpak_app_path = _flatpak_app_path(flatpak_info_path)
    if flatpak_app_path is not None:
        visible_host_dirs = _native_layer_dirs_from_app_files(flatpak_app_path)
        candidates.extend((path, path) for path in visible_host_dirs)
        for source_dir in source_dirs:
            try:
                relative = source_dir.resolve().relative_to(Path("/app"))
            except ValueError:
                continue
            candidates.append((flatpak_app_path / relative, source_dir))
    candidates.extend((path, path) for path in source_dirs)

    unique: list[tuple[Path, Path]] = []
    seen: set[Path] = set()
    for host_path, source_path in candidates:
        if host_path not in seen:
            unique.append((host_path, source_path))
            seen.add(host_path)
    return unique


def install_vulkan_layer_manifest(
    *,
    home: Path | str | None = None,
    layer_dirs: list[Path] | tuple[Path, ...] | None = None,
    flatpak_info_path: Path = Path("/.flatpak-info"),
) -> Path | None:
    candidates: list[tuple[Path, Path]] = list(
        _native_layer_dirs_for_host_manifest(flatpak_info_path)
        if layer_dirs is None
        else [(path, path) for path in layer_dirs]
    )
    if not candidates:
        return None
    host_layer_dir, source_layer_dir = candidates[0]
    target = _default_vulkan_manifest_path(home)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        _host_vulkan_manifest_text(
            host_layer_dir,
            source_layer_dir=source_layer_dir,
        ),
        encoding="utf-8",
    )
    target.chmod(0o644)
    return target


def _is_managed_vulkan_manifest(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return (
        "VK_LAYER_PENGUINBURNER_latency" in text
        and NATIVE_LAYER_LIBRARY in text
        and VULKAN_LAYER_ENABLE_ENV in text
    )


def uninstall_vulkan_layer_manifest(*, home: Path | str | None = None) -> Path | None:
    target = _default_vulkan_manifest_path(home)
    if not target.exists() or not _is_managed_vulkan_manifest(target):
        return None
    target.unlink()
    return target


def _wrapper_text(command_name: str) -> str:
    if command_name == "PENGUIN_BURNER":
        return _steam_wrapper_text()
    return _flatpak_command_wrapper_text(command_name)


def _flatpak_command_wrapper_text(command_name: str) -> str:
    return (
        "#!/usr/bin/env sh\n"
        f"# {MARKER}\n"
        "if [ \"$(id -u)\" = 0 ]; then\n"
        "    desktop_user=\"${PENGUIN_BURNER_Q2RTX_USER:-${SUDO_USER:-}}\"\n"
        "    if [ -n \"$desktop_user\" ] && command -v getent >/dev/null 2>&1; then\n"
        "        desktop_home=\"$(getent passwd \"$desktop_user\" | cut -d: -f6)\"\n"
        "        if [ -n \"$desktop_home\" ]; then\n"
        "            export HOME=\"$desktop_home\"\n"
        "            export XDG_DATA_HOME=\"${XDG_DATA_HOME:-$desktop_home/.local/share}\"\n"
        "        fi\n"
        "    fi\n"
        "fi\n"
        f'exec /usr/bin/flatpak run --user --command={command_name} {APP_ID} "$@"\n'
    )


def _steam_wrapper_text() -> str:
    return (
        "#!/usr/bin/env sh\n"
        f"# {MARKER}\n"
        "set -eu\n"
        "while [ \"$#\" -gt 0 ]; do\n"
        "    case \"$1\" in\n"
        "        --pb-overlay=*)\n"
        "            overlay_value=${1#--pb-overlay=}\n"
        "            case \"$overlay_value\" in\n"
        "                1|true|TRUE|yes|YES|on|ON|0|false|FALSE|no|NO|off|OFF)\n"
        "                    export PB_OVERLAY=\"$overlay_value\"\n"
        "                    export PENGUIN_BURNER_OVERLAY=\"$overlay_value\"\n"
        "                    ;;\n"
        "            esac\n"
        "            shift\n"
        "            ;;\n"
        "        *) break ;;\n"
        "    esac\n"
        "done\n"
        "if [ \"$#\" -eq 0 ]; then\n"
        "    echo \"Usage: $0 %command%\" >&2\n"
        "    exit 2\n"
        "fi\n"
        "if [ \"$(id -u)\" = 0 ]; then\n"
        "    desktop_user=\"${PENGUIN_BURNER_Q2RTX_USER:-${SUDO_USER:-}}\"\n"
        "    if [ -n \"$desktop_user\" ] && command -v getent >/dev/null 2>&1; then\n"
        "        desktop_home=\"$(getent passwd \"$desktop_user\" | cut -d: -f6)\"\n"
        "        if [ -n \"$desktop_home\" ]; then\n"
        "            export HOME=\"$desktop_home\"\n"
        "            export XDG_DATA_HOME=\"${XDG_DATA_HOME:-$desktop_home/.local/share}\"\n"
        "        fi\n"
        "    fi\n"
        "fi\n"
        "run_flatpak_clean() (\n"
        "    unset LD_PRELOAD LD_LIBRARY_PATH LD_AUDIT\n"
        "    exec /usr/bin/flatpak \"$@\"\n"
        ")\n"
        "cache_dir=\"${XDG_CACHE_HOME:-$HOME/.cache}/penguin-burner\"\n"
        "config_dir=\"${XDG_CONFIG_HOME:-$HOME/.config}/PenguinBurner\"\n"
        "mkdir -p \"$cache_dir\" \"$config_dir\" 2>/dev/null || true\n"
        "app_id=\"${PENGUIN_BURNER_FLATPAK_APP_ID:-io.github.jpietek.PenguinBurner}\"\n"
        "app_files=\"${PENGUIN_BURNER_FLATPAK_APP_PATH:-}\"\n"
        "if [ -z \"$app_files\" ] && [ -x /usr/bin/flatpak ]; then\n"
        "    app_location=\"$(run_flatpak_clean info --user --show-location \"$app_id\" 2>/dev/null || run_flatpak_clean info --show-location \"$app_id\" 2>/dev/null || true)\"\n"
        "    if [ -n \"$app_location\" ]; then\n"
        "        app_files=\"$app_location/files\"\n"
        "    fi\n"
        "fi\n"
        "steam_app_id=\"${SteamAppId:-${STEAM_COMPAT_APP_ID:-${SteamGameId:-}}}\"\n"
        "steam_account_name=\"${SteamUser:-${SteamAppUser:-}}\"\n"
        "case \"$steam_app_id\" in\n"
        "    ''|*[!0-9]*) ;;\n"
        "    *)\n"
        "        if [ -x /usr/bin/flatpak ]; then\n"
        "            run_flatpak_clean run --cwd=/app --command=python3 \"$app_id\" \\\n"
        "                -m integrations.steam.game_runtime \\\n"
        "                --watch-pid \"$$\" --app-id \"$steam_app_id\" \\\n"
        "                --account-name \"$steam_account_name\" || true\n"
        "        fi\n"
        "        ;;\n"
        "esac\n"
        "site_packages=\"\"\n"
        "if [ -n \"$app_files\" ]; then\n"
        "    for candidate in \"$app_files\"/lib/python*/site-packages; do\n"
        "        if [ -d \"$candidate\" ]; then\n"
        "            site_packages=\"$candidate\"\n"
        "        fi\n"
        "    done\n"
        "fi\n"
        "native_layer_dir=\"${PENGUIN_BURNER_NATIVE_LAYER_DIR:-}\"\n"
        "if [ -z \"$native_layer_dir\" ] && [ -n \"$site_packages\" ]; then\n"
        "    native_layer_dir=\"$site_packages/overlay/native_layer\"\n"
        "fi\n"
        "if [ -f \"$native_layer_dir/VkLayer_PENGUINBURNER_latency.json\" ] && [ -f \"$native_layer_dir/libVkLayer_penguinburner_latency.so\" ]; then\n"
        "    export PENGUIN_BURNER_NATIVE_LAYER_DIR=\"$native_layer_dir\"\n"
        "    case \":${VK_ADD_IMPLICIT_LAYER_PATH:-}:\" in\n"
        "        *:\"$native_layer_dir\":*) ;;\n"
        "        *) export VK_ADD_IMPLICIT_LAYER_PATH=\"$native_layer_dir${VK_ADD_IMPLICIT_LAYER_PATH:+:$VK_ADD_IMPLICIT_LAYER_PATH}\" ;;\n"
        "    esac\n"
        "    case \",${VK_LOADER_LAYERS_ENABLE:-},\" in\n"
        "        *,VK_LAYER_PENGUINBURNER_latency,*) ;;\n"
        "        *) export VK_LOADER_LAYERS_ENABLE=\"VK_LAYER_PENGUINBURNER_latency${VK_LOADER_LAYERS_ENABLE:+,$VK_LOADER_LAYERS_ENABLE}\" ;;\n"
        "    esac\n"
        "fi\n"
        "dll_has_marker_log_flag() {\n"
        "    [ -f \"$1\" ] || return 1\n"
        "    LC_ALL=C grep -a -q 'DXVK_NVAPI_LATENCY_MARKER_LOG' \"$1\" 2>/dev/null\n"
        "}\n"
        "proton_root_has_marker_log_flag() {\n"
        "    root=\"$1\"\n"
        "    for candidate in \\\n"
        "        \"$root/files/lib/wine/nvapi/x86_64-windows/nvapi64.dll\" \\\n"
        "        \"$root/files/lib/wine/nvapi/i386-windows/nvapi.dll\" \\\n"
        "        \"$root/files/lib/wine/nvidia-libs/nvapi/x86_64-windows/nvapi64.dll\" \\\n"
        "        \"$root/files/lib/wine/nvidia-libs/nvapi/i386-windows/nvapi.dll\"\n"
        "    do\n"
        "        dll_has_marker_log_flag \"$candidate\" && return 0\n"
        "    done\n"
        "    return 1\n"
        "}\n"
        "dxvk_nvapi_marker_log_supported() {\n"
        "    prefix_has_nvapi=0\n"
        "    if [ -n \"${STEAM_COMPAT_DATA_PATH:-}\" ]; then\n"
        "        windows=\"$STEAM_COMPAT_DATA_PATH/pfx/drive_c/windows\"\n"
        "        for candidate in \\\n"
        "            \"$windows/system32/nvapi64.dll\" \\\n"
        "            \"$windows/syswow64/nvapi.dll\"\n"
        "        do\n"
        "            if [ -f \"$candidate\" ]; then\n"
        "                prefix_has_nvapi=1\n"
        "                dll_has_marker_log_flag \"$candidate\" && return 0\n"
        "            fi\n"
        "        done\n"
        "        [ \"$prefix_has_nvapi\" = 0 ] || return 1\n"
        "    fi\n"
        "    old_ifs=$IFS\n"
        "    IFS=:\n"
        "    for root in ${STEAM_COMPAT_TOOL_PATHS:-}${STEAM_COMPAT_TOOL_PATH:+:$STEAM_COMPAT_TOOL_PATH}; do\n"
        "        [ -n \"$root\" ] || continue\n"
        "        proton_root_has_marker_log_flag \"$root\" && IFS=$old_ifs && return 0\n"
        "    done\n"
        "    IFS=$old_ifs\n"
        "    for arg in \"$@\"; do\n"
        "        case \"$arg\" in\n"
        "            */proton|proton)\n"
        "                root=$(dirname \"$arg\")\n"
        "                proton_root_has_marker_log_flag \"$root\" && return 0\n"
        "                ;;\n"
        "        esac\n"
        "    done\n"
        "    return 1\n"
        "}\n"
        "export PENGUIN_BURNER=\"${PENGUIN_BURNER:-1}\"\n"
        "export PENGUIN_BURNER_LATENCY_LAYER=\"${PENGUIN_BURNER_LATENCY_LAYER:-1}\"\n"
        "if [ -z \"${PENGUIN_BURNER_OVERLAY+x}\" ] && [ -n \"${PB_OVERLAY:-}\" ]; then\n"
        "    export PENGUIN_BURNER_OVERLAY=\"$PB_OVERLAY\"\n"
        "fi\n"
        "export PENGUIN_BURNER_OVERLAY=\"${PENGUIN_BURNER_OVERLAY:-auto}\"\n"
        "export DXVK_NVAPI_VKREFLEX=\"${DXVK_NVAPI_VKREFLEX:-1}\"\n"
        "export PROTON_ENABLE_NVAPI=\"${PROTON_ENABLE_NVAPI:-1}\"\n"
        "export PROTON_HIDE_NVIDIA_GPU=\"${PROTON_HIDE_NVIDIA_GPU:-0}\"\n"
        "case \"${PENGUIN_BURNER_INGAME_LATENCY:-${PB_INGAME_LATENCY:-}}\" in\n"
        "    1|true|TRUE|yes|YES|on|ON)\n"
        "        export PENGUIN_BURNER_LATENCY_DISPLAY=\"${PENGUIN_BURNER_LATENCY_DISPLAY:-1}\"\n"
        "        export PENGUIN_BURNER_LATENCY_INJECT_PRESENT_ID=\"${PENGUIN_BURNER_LATENCY_INJECT_PRESENT_ID:-1}\"\n"
        "        case \"${DXVK_NVAPI_LOG_LEVEL:-}\" in\n"
        "            trace) ;;\n"
        "            *)\n"
        "                case \"${DXVK_NVAPI_LATENCY_MARKER_LOG:-}\" in\n"
        "                    1|true|TRUE|yes|YES|on|ON) ;;\n"
        "                    *)\n"
        "                        if dxvk_nvapi_marker_log_supported \"$@\"; then\n"
        "                            export DXVK_NVAPI_LATENCY_MARKER_LOG=\"${DXVK_NVAPI_LATENCY_MARKER_LOG:-1}\"\n"
        "                        else\n"
        "                            export DXVK_NVAPI_LOG_LEVEL=\"${DXVK_NVAPI_LOG_LEVEL:-trace}\"\n"
        "                        fi\n"
        "                        ;;\n"
        "                esac\n"
        "                ;;\n"
        "        esac\n"
        "        trace_fifo=\"$cache_dir/nvapi-trace.fifo\"\n"
        "        if [ ! -e \"$trace_fifo\" ]; then\n"
        "            mkfifo -m 600 \"$trace_fifo\" 2>/dev/null || true\n"
        "        fi\n"
        "        if [ -p \"$trace_fifo\" ]; then\n"
        "            if exec 3<>\"$trace_fifo\" 2>/dev/null; then\n"
        "                exec 2>&3\n"
        "                exec 3>&-\n"
        "            fi\n"
        "        fi\n"
        "        ;;\n"
        "esac\n"
        "export PENGUIN_BURNER_LATENCY_SOCKET=\"${PENGUIN_BURNER_LATENCY_SOCKET:-$cache_dir/latency.sock}\"\n"
        "export PENGUIN_BURNER_OVERLAY_STATE=\"${PENGUIN_BURNER_OVERLAY_STATE:-$cache_dir/overlay-state.txt}\"\n"
        "export PENGUIN_BURNER_OVERLAY_TEXT=\"${PENGUIN_BURNER_OVERLAY_TEXT:-$cache_dir/overlay-text.txt}\"\n"
        "export PENGUIN_BURNER_OVERLAY_CONFIG=\"${PENGUIN_BURNER_OVERLAY_CONFIG:-$config_dir/overlay.toml}\"\n"
        "unset MANGOHUD MANGOHUD_CONFIG MANGOHUD_DLSYM MANGOAPP MANGOAPP_CONFIG\n"
        "exec \"$@\"\n"
    )


def install_wrappers(bin_dir: Path, *, force: bool = False) -> list[Path]:
    bin_dir = bin_dir.expanduser()
    bin_dir.mkdir(parents=True, exist_ok=True)
    installed = []
    for command_name in WRAPPERS:
        target = bin_dir / command_name
        if target.exists() and not force and not _is_managed_wrapper(target):
            raise RuntimeError(
                f"refusing to overwrite existing command: {target} "
                "(rerun with --force)"
            )
        target.write_text(_wrapper_text(command_name), encoding="utf-8")
        target.chmod(
            stat.S_IRUSR
            | stat.S_IWUSR
            | stat.S_IXUSR
            | stat.S_IRGRP
            | stat.S_IXGRP
            | stat.S_IROTH
            | stat.S_IXOTH
        )
        installed.append(target)
    return installed


def uninstall_wrappers(bin_dir: Path) -> tuple[list[Path], list[Path]]:
    removed = []
    skipped = []
    for command_name in WRAPPERS:
        target = bin_dir.expanduser() / command_name
        if not target.exists():
            continue
        if not _is_managed_wrapper(target):
            skipped.append(target)
            continue
        target.unlink()
        removed.append(target)
    return removed, skipped


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.uninstall:
            removed, skipped = uninstall_wrappers(args.bin_dir)
            removed_manifest = uninstall_vulkan_layer_manifest()
            for path in removed:
                print(f"removed {path}")
            if removed_manifest is not None:
                print(f"removed {removed_manifest}")
            for path in skipped:
                print(f"skipped non-managed command: {path}", file=sys.stderr)
            return 0

        installed = install_wrappers(args.bin_dir, force=args.force)
        manifest = install_vulkan_layer_manifest()
        for path in installed:
            print(f"installed {path}")
        if manifest is None:
            print(
                "warning: PenguinBurner native Vulkan layer was not found; "
                "Steam overlay layer registration was skipped",
                file=sys.stderr,
            )
        else:
            print(f"installed {manifest}")
        if "FLATPAK_ID" not in os.environ:
            path_entries = os.environ.get("PATH", "").split(os.pathsep)
            if str(args.bin_dir.expanduser()) not in path_entries:
                print(
                    f"warning: {args.bin_dir.expanduser()} is not on PATH; "
                    "add it to use pburn directly",
                    file=sys.stderr,
                )
        return 0
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
