from __future__ import annotations

import argparse
import os
from pathlib import Path
import stat
import sys


APP_ID = "io.github.jpietek.PenguinBurner"
MARKER = "Generated by PenguinBurner Flatpak wrapper installer"
WRAPPERS = (
    "penguin-burner",
    "pburn",
    "penguin-burner-ui",
    "pburn-ui",
    "penguin-burner-cli",
    "pburn-cli",
    "PENGUIN_BURNER",
)


def _default_bin_dir() -> Path:
    override = os.environ.get("PENGUIN_BURNER_FLATPAK_WRAPPER_BIN_DIR")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".local" / "bin"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Install host PATH wrappers for the PenguinBurner Flatpak. "
            "The wrappers forward to flatpak run --command=<name> "
            f"{APP_ID}."
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing non-PenguinBurner wrapper files",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="remove wrappers previously created by this command",
    )
    parser.add_argument(
        "--bin-dir",
        type=Path,
        default=_default_bin_dir(),
        help="install/remove wrappers in DIR (default: ~/.local/bin)",
        metavar="DIR",
    )
    return parser


def _is_managed_wrapper(path: Path) -> bool:
    try:
        return path.is_file() and MARKER in path.read_text(
            encoding="utf-8", errors="replace"
        )
    except OSError:
        return False


def _wrapper_text(command_name: str) -> str:
    return (
        "#!/usr/bin/env sh\n"
        f"# {MARKER}\n"
        "if [ \"$(id -u)\" = 0 ]; then\n"
        "    desktop_user=\"${PENGUIN_BURNER_Q2RTX_USER:-${SUDO_USER:-}}\"\n"
        "    if [ -n \"$desktop_user\" ] && command -v getent >/dev/null 2>&1; then\n"
        "        desktop_home=\"$(getent passwd \"$desktop_user\" | cut -d: -f6)\"\n"
        "        if [ -n \"$desktop_home\" ]; then\n"
        "            export HOME=\"$desktop_home\"\n"
        "            export XDG_DATA_HOME=\"${XDG_DATA_HOME:-$desktop_home/.local/share}\"\n"
        "        fi\n"
        "    fi\n"
        "fi\n"
        f'exec /usr/bin/flatpak run --user --command={command_name} {APP_ID} "$@"\n'
    )


def install_wrappers(bin_dir: Path, *, force: bool = False) -> list[Path]:
    bin_dir = bin_dir.expanduser()
    bin_dir.mkdir(parents=True, exist_ok=True)
    installed = []
    for command_name in WRAPPERS:
        target = bin_dir / command_name
        if target.exists() and not force and not _is_managed_wrapper(target):
            raise RuntimeError(
                f"refusing to overwrite existing command: {target} "
                "(rerun with --force)"
            )
        target.write_text(_wrapper_text(command_name), encoding="utf-8")
        target.chmod(
            stat.S_IRUSR
            | stat.S_IWUSR
            | stat.S_IXUSR
            | stat.S_IRGRP
            | stat.S_IXGRP
            | stat.S_IROTH
            | stat.S_IXOTH
        )
        installed.append(target)
    return installed


def uninstall_wrappers(bin_dir: Path) -> tuple[list[Path], list[Path]]:
    removed = []
    skipped = []
    for command_name in WRAPPERS:
        target = bin_dir.expanduser() / command_name
        if not target.exists():
            continue
        if not _is_managed_wrapper(target):
            skipped.append(target)
            continue
        target.unlink()
        removed.append(target)
    return removed, skipped


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.uninstall:
            removed, skipped = uninstall_wrappers(args.bin_dir)
            for path in removed:
                print(f"removed {path}")
            for path in skipped:
                print(f"skipped non-managed command: {path}", file=sys.stderr)
            return 0

        installed = install_wrappers(args.bin_dir, force=args.force)
        for path in installed:
            print(f"installed {path}")
        if "FLATPAK_ID" not in os.environ:
            path_entries = os.environ.get("PATH", "").split(os.pathsep)
            if str(args.bin_dir.expanduser()) not in path_entries:
                print(
                    f"warning: {args.bin_dir.expanduser()} is not on PATH; "
                    "add it to use pburn directly",
                    file=sys.stderr,
                )
        return 0
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
