#!/usr/bin/env bash

# Install the *published* Flatpak from the live Pages repository inside a
# disposable distro container: remote metadata, GPG signature, the ostree
# pull, the freedesktop runtime dependency, and the wrapper
# install/--uninstall round trip (issue #19's leftover-files complaint).
#
# Unlike check-flatpak-install-smoke.sh this tests the deployed channel, not
# the current tree, so it is a scheduled channel-health check rather than a
# pre-publish gate. publish-flatpak-pages.sh already rehearses install and
# update locally at publish time; this re-proves the public URL afterwards on
# each host distro's flatpak/bubblewrap stack.

set -euo pipefail

APP_ID="io.github.jpietek.PenguinBurner"
ENGINE="${PENGUIN_BURNER_CONTAINER_ENGINE:-docker}"
NETWORK="${PENGUIN_BURNER_CONTAINER_NETWORK:-host}"
REPO_URL="${PENGUIN_BURNER_FLATPAK_REPO_URL:-https://jpietek.github.io/PenguinBurner/penguin-burner.flatpakrepo}"
WRAPPER_MARKER="Generated by PenguinBurner Flatpak wrapper installer"
VULKAN_MANIFEST_NAME="VkLayer_PENGUINBURNER_latency.json"

if ! command -v "$ENGINE" >/dev/null 2>&1; then
    echo "missing required command: $ENGINE" >&2
    exit 1
fi

scenario_image() {
    case "$1" in
        fedora) echo "fedora:latest" ;;
        ubuntu-lts) echo "ubuntu:24.04" ;;
        arch) echo "archlinux:latest" ;;
        *)
            echo "unknown scenario: $1 (expected fedora, ubuntu-lts, or arch)" >&2
            exit 2
            ;;
    esac
}

scenario_bootstrap() {
    case "$1" in
        fedora)
            echo "dnf -q install -y flatpak dbus-daemon >/dev/null"
            ;;
        ubuntu-lts)
            echo "apt-get update -qq >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y flatpak ca-certificates dbus >/dev/null"
            ;;
        arch)
            echo "pacman -Sy --noconfirm --needed flatpak dbus >/dev/null"
            ;;
    esac
}

# Older flatpak versions (ubuntu-lts ships 1.14) refuse `flatpak run` when the
# system D-Bus is unreachable; distro containers boot without one, so start it.
# Containers also lack systemd, so bus activation of AccountsService (which
# flatpak's parental-controls support queries on `flatpak run`) can only fail;
# where the distro ships it (arch), that failure is a fatal spawn error, so
# drop the activation file to get the clean no-such-service = no-parental-
# controls path every real host without AccountsService takes.
CONTAINER_SYSTEM_BUS_SNIPPET='
if [ ! -S /run/dbus/system_bus_socket ] && command -v dbus-daemon >/dev/null 2>&1; then
    mkdir -p /run/dbus
    dbus-daemon --system --fork
fi
rm -f /usr/share/dbus-1/system-services/org.freedesktop.Accounts.service
'

run_scenario() {
    local scenario="$1"
    local image bootstrap
    image="$(scenario_image "$scenario")"
    bootstrap="$(scenario_bootstrap "$scenario")"

    echo "==> flatpak channel install ($scenario scenario, $image, $REPO_URL)"
    # --privileged for bubblewrap: `flatpak run` sets up the sandbox inside
    # the container.
    "$ENGINE" run --rm --privileged --security-opt label=disable \
        --network "$NETWORK" \
        -e APP_ID="$APP_ID" \
        -e REPO_URL="$REPO_URL" \
        -e WRAPPER_MARKER="$WRAPPER_MARKER" \
        -e VULKAN_MANIFEST_NAME="$VULKAN_MANIFEST_NAME" \
        "$image" \
        bash -euo pipefail -c '
            '"$bootstrap"'
            '"$CONTAINER_SYSTEM_BUS_SNIPPET"'

            # The published repo carries only the app; its freedesktop
            # runtime dependency resolves from flathub, which user systems
            # already have configured.
            flatpak remote-add --user --if-not-exists flathub \
                https://dl.flathub.org/repo/flathub.flatpakrepo
            flatpak remote-add --user --if-not-exists penguinburner "$REPO_URL"
            flatpak install --user -y penguinburner "$APP_ID"
            echo "installed: $(flatpak info --user "$APP_ID" | sed -n "s/^ *Version: */version /p")"

            flatpak run --user --command=penguin-burner-cli "$APP_ID" --help >/dev/null
            flatpak run --user --command=pburn-cli "$APP_ID" --help >/dev/null

            bin_dir="$HOME/.local/bin"
            manifest="$HOME/.local/share/vulkan/implicit_layer.d/$VULKAN_MANIFEST_NAME"
            flatpak run --user --command=penguin-burner-install-wrappers \
                "$APP_ID" --bin-dir "$bin_dir"
            for bin in penguin-burner pburn penguin-burner-cli pburn-cli PENGUIN_BURNER; do
                test -x "$bin_dir/$bin"
                grep -Fq "$WRAPPER_MARKER" "$bin_dir/$bin"
            done
            test -f "$manifest"

            flatpak run --user --command=penguin-burner-install-wrappers \
                "$APP_ID" --uninstall --bin-dir "$bin_dir"
            for bin in penguin-burner pburn penguin-burner-cli pburn-cli PENGUIN_BURNER; do
                if [ -e "$bin_dir/$bin" ]; then
                    echo "uninstall left $bin_dir/$bin behind" >&2
                    exit 1
                fi
            done
            if [ -e "$manifest" ]; then
                echo "uninstall left $manifest behind" >&2
                exit 1
            fi
            leftovers="$(grep -Frl "$WRAPPER_MARKER" "$bin_dir" 2>/dev/null || true)"
            if [ -n "$leftovers" ]; then
                echo "uninstall left managed wrappers behind:" >&2
                echo "$leftovers" >&2
                exit 1
            fi

            echo "channel install OK: $(flatpak info --user "$APP_ID" | sed -n "s/^ *Version: *//p")"
        '
}

scenarios=("$@")
if [[ ${#scenarios[@]} -eq 0 ]]; then
    scenarios=(fedora)
fi

for scenario in "${scenarios[@]}"; do
    scenario_image "$scenario" >/dev/null
done
for scenario in "${scenarios[@]}"; do
    run_scenario "$scenario"
done
