#!/usr/bin/env bash

set -euo pipefail

APP_ID="${PENGUIN_BURNER_FLATPAK_APP_ID:-io.github.jpietek.PenguinBurner}"
BIN_DIR="${PENGUIN_BURNER_FLATPAK_WRAPPER_BIN_DIR:-$HOME/.local/bin}"
MARKER="Generated by PenguinBurner Flatpak wrapper installer"
MODE="install"
FORCE=0
VULKAN_LAYER_MANIFEST="VkLayer_PENGUINBURNER_latency.json"
VULKAN_LAYER_LIBRARY="libVkLayer_penguinburner_latency.so"
WRAPPERS=(
    penguin-burner
    pburn
    penguin-burner-ui
    pburn-ui
    penguin-burner-cli
    pburn-cli
    PENGUIN_BURNER
)

usage() {
    cat <<EOF
Usage: $0 [--force] [--uninstall] [--bin-dir DIR]

Install host PATH wrappers for the PenguinBurner Flatpak:
  penguin-burner, pburn, penguin-burner-ui, pburn-ui,
  penguin-burner-cli, pburn-cli, PENGUIN_BURNER

The GUI/CLI wrappers forward to:
  flatpak run --command=<name> $APP_ID

PENGUIN_BURNER is a Steam game wrapper: it sets host overlay environment and
then runs the game command directly.

Options:
  --force       overwrite existing non-PenguinBurner wrapper files
  --uninstall   remove wrappers previously created by this script
  --bin-dir DIR install/remove wrappers in DIR (default: $BIN_DIR)
EOF
}

die() {
    echo "error: $*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

is_managed_wrapper() {
    local path="$1"
    test -f "$path" && grep -Fq "$MARKER" "$path"
}

vulkan_manifest_path() {
    printf '%s\n' "$HOME/.local/share/vulkan/implicit_layer.d/$VULKAN_LAYER_MANIFEST"
}

find_native_layer_dir() {
    local app_location app_files site_packages candidate native_layer_dir
    app_location="$(flatpak info --user --show-location "$APP_ID" 2>/dev/null || flatpak info --show-location "$APP_ID" 2>/dev/null || true)"
    if [[ -z "$app_location" ]]; then
        return 0
    fi
    app_files="$app_location/files"
    site_packages=""
    for candidate in "$app_files"/lib/python*/site-packages; do
        if [[ -d "$candidate" ]]; then
            site_packages="$candidate"
        fi
    done
    if [[ -z "$site_packages" ]]; then
        return 0
    fi
    native_layer_dir="$site_packages/overlay/native_layer"
    if [[ -f "$native_layer_dir/$VULKAN_LAYER_MANIFEST" && -f "$native_layer_dir/$VULKAN_LAYER_LIBRARY" ]]; then
        printf '%s\n' "$native_layer_dir"
    fi
}

install_vulkan_layer_manifest() {
    local native_layer_dir target
    native_layer_dir="$(find_native_layer_dir)"
    if [[ -z "$native_layer_dir" ]]; then
        echo "warning: PenguinBurner native Vulkan layer was not found; Steam overlay layer registration was skipped" >&2
        return
    fi

    target="$(vulkan_manifest_path)"
    mkdir -p "$(dirname "$target")"
    cat >"$target" <<EOF
{
  "file_format_version": "1.2.1",
  "layer": {
    "name": "VK_LAYER_PENGUINBURNER_latency",
    "type": "GLOBAL",
    "api_version": "1.4.0",
    "library_path": "$native_layer_dir/$VULKAN_LAYER_LIBRARY",
    "library_arch": "64",
    "implementation_version": "1",
    "description": "PenguinBurner latency telemetry observer",
    "functions": {
      "vkGetInstanceProcAddr": "vkGetInstanceProcAddr",
      "vkGetDeviceProcAddr": "vkGetDeviceProcAddr"
    },
    "enable_environment": {
      "PENGUIN_BURNER": "1"
    },
    "disable_environment": {
      "DISABLE_PENGUIN_BURNER_LATENCY_LAYER": ""
    }
  }
}
EOF
    chmod 644 "$target"
    echo "installed $target"
}

uninstall_vulkan_layer_manifest() {
    local target
    target="$(vulkan_manifest_path)"
    if [[ -f "$target" ]] \
        && grep -Fq "VK_LAYER_PENGUINBURNER_latency" "$target" \
        && grep -Fq "$VULKAN_LAYER_LIBRARY" "$target"; then
        rm -f "$target"
        echo "removed $target"
    fi
}

install_wrapper() {
    local command_name="$1"
    local target="$BIN_DIR/$command_name"

    if [[ -e "$target" && "$FORCE" != "1" ]] && ! is_managed_wrapper "$target"; then
        die "refusing to overwrite existing command: $target (rerun with --force)"
    fi

    if [[ "$command_name" == "PENGUIN_BURNER" ]]; then
        install_steam_wrapper "$target"
    else
        cat >"$target" <<EOF
#!/usr/bin/env sh
# $MARKER
exec flatpak run --command=$command_name $APP_ID "\$@"
EOF
    fi
    chmod 755 "$target"
    echo "installed $target"
}

install_steam_wrapper() {
    local target="$1"
    cat >"$target" <<'EOF'
#!/usr/bin/env sh
# Generated by PenguinBurner Flatpak wrapper installer
set -eu
while [ "$#" -gt 0 ]; do
    case "$1" in
        --pb-overlay=*)
            overlay_value=${1#--pb-overlay=}
            case "$overlay_value" in
                1|true|TRUE|yes|YES|on|ON|0|false|FALSE|no|NO|off|OFF)
                    export PB_OVERLAY="$overlay_value"
                    export PENGUIN_BURNER_OVERLAY="$overlay_value"
                    ;;
            esac
            shift
            ;;
        *) break ;;
    esac
done
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 %command%" >&2
    exit 2
fi
run_flatpak_clean() (
    unset LD_PRELOAD LD_LIBRARY_PATH LD_AUDIT
    exec /usr/bin/flatpak "$@"
)
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/penguin-burner"
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/PenguinBurner"
mkdir -p "$cache_dir" "$config_dir" 2>/dev/null || true
app_id="${PENGUIN_BURNER_FLATPAK_APP_ID:-io.github.jpietek.PenguinBurner}"
app_files="${PENGUIN_BURNER_FLATPAK_APP_PATH:-}"
if [ -z "$app_files" ] && [ -x /usr/bin/flatpak ]; then
    app_location="$(run_flatpak_clean info --user --show-location "$app_id" 2>/dev/null || run_flatpak_clean info --show-location "$app_id" 2>/dev/null || true)"
    if [ -n "$app_location" ]; then
        app_files="$app_location/files"
    fi
fi
steam_app_id="${SteamAppId:-${STEAM_COMPAT_APP_ID:-${SteamGameId:-}}}"
steam_account_name="${SteamUser:-${SteamAppUser:-}}"
case "$steam_app_id" in
    ''|*[!0-9]*) ;;
    *)
        if [ -x /usr/bin/flatpak ]; then
            run_flatpak_clean run --cwd=/app --command=python3 "$app_id" \
                -m integrations.steam.game_runtime \
                --watch-pid "$$" --app-id "$steam_app_id" \
                --account-name "$steam_account_name" || true
        fi
        ;;
esac
site_packages=""
if [ -n "$app_files" ]; then
    for candidate in "$app_files"/lib/python*/site-packages; do
        if [ -d "$candidate" ]; then
            site_packages="$candidate"
        fi
    done
fi
native_layer_dir="${PENGUIN_BURNER_NATIVE_LAYER_DIR:-}"
if [ -z "$native_layer_dir" ] && [ -n "$site_packages" ]; then
    native_layer_dir="$site_packages/overlay/native_layer"
fi
if [ -f "$native_layer_dir/VkLayer_PENGUINBURNER_latency.json" ] && [ -f "$native_layer_dir/libVkLayer_penguinburner_latency.so" ]; then
    export PENGUIN_BURNER_NATIVE_LAYER_DIR="$native_layer_dir"
    export VK_ADD_IMPLICIT_LAYER_PATH="$native_layer_dir${VK_ADD_IMPLICIT_LAYER_PATH:+:$VK_ADD_IMPLICIT_LAYER_PATH}"
    export VK_LOADER_LAYERS_ENABLE="VK_LAYER_PENGUINBURNER_latency${VK_LOADER_LAYERS_ENABLE:+,$VK_LOADER_LAYERS_ENABLE}"
fi
dll_has_marker_log_flag() {
    [ -f "$1" ] || return 1
    LC_ALL=C grep -a -q 'DXVK_NVAPI_LATENCY_MARKER_LOG' "$1" 2>/dev/null
}
proton_root_has_marker_log_flag() {
    root="$1"
    for candidate in \
        "$root/files/lib/wine/nvapi/x86_64-windows/nvapi64.dll" \
        "$root/files/lib/wine/nvapi/i386-windows/nvapi.dll" \
        "$root/files/lib/wine/nvidia-libs/nvapi/x86_64-windows/nvapi64.dll" \
        "$root/files/lib/wine/nvidia-libs/nvapi/i386-windows/nvapi.dll"
    do
        dll_has_marker_log_flag "$candidate" && return 0
    done
    return 1
}
dxvk_nvapi_marker_log_supported() {
    prefix_has_nvapi=0
    if [ -n "${STEAM_COMPAT_DATA_PATH:-}" ]; then
        windows="$STEAM_COMPAT_DATA_PATH/pfx/drive_c/windows"
        for candidate in \
            "$windows/system32/nvapi64.dll" \
            "$windows/syswow64/nvapi.dll"
        do
            if [ -f "$candidate" ]; then
                prefix_has_nvapi=1
                dll_has_marker_log_flag "$candidate" && return 0
            fi
        done
        [ "$prefix_has_nvapi" = 0 ] || return 1
    fi
    old_ifs=$IFS
    IFS=:
    for root in ${STEAM_COMPAT_TOOL_PATHS:-}${STEAM_COMPAT_TOOL_PATH:+:$STEAM_COMPAT_TOOL_PATH}; do
        [ -n "$root" ] || continue
        proton_root_has_marker_log_flag "$root" && IFS=$old_ifs && return 0
    done
    IFS=$old_ifs
    for arg in "$@"; do
        case "$arg" in
            */proton|proton)
                root=$(dirname "$arg")
                proton_root_has_marker_log_flag "$root" && return 0
                ;;
        esac
    done
    return 1
}
export PENGUIN_BURNER="${PENGUIN_BURNER:-1}"
export PENGUIN_BURNER_LATENCY_LAYER="${PENGUIN_BURNER_LATENCY_LAYER:-1}"
if [ -z "${PENGUIN_BURNER_OVERLAY+x}" ] && [ -n "${PB_OVERLAY:-}" ]; then
    export PENGUIN_BURNER_OVERLAY="$PB_OVERLAY"
fi
export PENGUIN_BURNER_OVERLAY="${PENGUIN_BURNER_OVERLAY:-auto}"
export DXVK_NVAPI_VKREFLEX="${DXVK_NVAPI_VKREFLEX:-1}"
export PROTON_ENABLE_NVAPI="${PROTON_ENABLE_NVAPI:-1}"
export PROTON_HIDE_NVIDIA_GPU="${PROTON_HIDE_NVIDIA_GPU:-0}"
case "${PENGUIN_BURNER_INGAME_LATENCY:-${PB_INGAME_LATENCY:-}}" in
    1|true|TRUE|yes|YES|on|ON)
        export PENGUIN_BURNER_LATENCY_DISPLAY="${PENGUIN_BURNER_LATENCY_DISPLAY:-1}"
        export PENGUIN_BURNER_LATENCY_INJECT_PRESENT_ID="${PENGUIN_BURNER_LATENCY_INJECT_PRESENT_ID:-1}"
        case "${DXVK_NVAPI_LOG_LEVEL:-}" in
            trace) ;;
            *)
                case "${DXVK_NVAPI_LATENCY_MARKER_LOG:-}" in
                    1|true|TRUE|yes|YES|on|ON) ;;
                    *)
                        if dxvk_nvapi_marker_log_supported "$@"; then
                            export DXVK_NVAPI_LATENCY_MARKER_LOG="${DXVK_NVAPI_LATENCY_MARKER_LOG:-1}"
                        else
                            export DXVK_NVAPI_LOG_LEVEL="${DXVK_NVAPI_LOG_LEVEL:-trace}"
                        fi
                        ;;
                esac
                ;;
        esac
        trace_fifo="$cache_dir/nvapi-trace.fifo"
        if [ ! -e "$trace_fifo" ]; then
            mkfifo -m 600 "$trace_fifo" 2>/dev/null || true
        fi
        if [ -p "$trace_fifo" ]; then
            if exec 3<>"$trace_fifo" 2>/dev/null; then
                exec 2>&3
                exec 3>&-
            fi
        fi
        ;;
esac
export PENGUIN_BURNER_LATENCY_SOCKET="${PENGUIN_BURNER_LATENCY_SOCKET:-$cache_dir/latency.sock}"
export PENGUIN_BURNER_OVERLAY_STATE="${PENGUIN_BURNER_OVERLAY_STATE:-$cache_dir/overlay-state.txt}"
export PENGUIN_BURNER_OVERLAY_TEXT="${PENGUIN_BURNER_OVERLAY_TEXT:-$cache_dir/overlay-text.txt}"
export PENGUIN_BURNER_OVERLAY_CONFIG="${PENGUIN_BURNER_OVERLAY_CONFIG:-$config_dir/overlay.toml}"
unset MANGOHUD MANGOHUD_CONFIG MANGOHUD_DLSYM MANGOAPP MANGOAPP_CONFIG
exec "$@"
EOF
}

uninstall_wrapper() {
    local command_name="$1"
    local target="$BIN_DIR/$command_name"

    if [[ ! -e "$target" ]]; then
        return
    fi
    if ! is_managed_wrapper "$target"; then
        echo "skipped non-managed command: $target" >&2
        return
    fi
    rm -f "$target"
    echo "removed $target"
}

path_contains_bin_dir() {
    local entry
    IFS=: read -r -a path_entries <<<"${PATH:-}"
    for entry in "${path_entries[@]}"; do
        if [[ "$entry" == "$BIN_DIR" ]]; then
            return 0
        fi
    done
    return 1
}

while (($#)); do
    case "$1" in
        --force)
            FORCE=1
            ;;
        --uninstall)
            MODE="uninstall"
            ;;
        --bin-dir)
            shift
            [[ $# -gt 0 ]] || die "--bin-dir requires a directory"
            BIN_DIR="$1"
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
    shift
done

require_command flatpak

if [[ "$MODE" == "install" ]]; then
    flatpak info "$APP_ID" >/dev/null 2>&1 || die "Flatpak app is not installed: $APP_ID"
    mkdir -p "$BIN_DIR"
    for wrapper in "${WRAPPERS[@]}"; do
        install_wrapper "$wrapper"
    done
    install_vulkan_layer_manifest
    if ! path_contains_bin_dir; then
        echo "warning: $BIN_DIR is not on PATH; add it to use pburn directly" >&2
    fi
else
    for wrapper in "${WRAPPERS[@]}"; do
        uninstall_wrapper "$wrapper"
    done
    uninstall_vulkan_layer_manifest
fi
