#!/usr/bin/env bash

set -euo pipefail

APP_ID="${PENGUIN_BURNER_FLATPAK_APP_ID:-io.github.jpietek.PenguinBurner}"
BIN_DIR="${PENGUIN_BURNER_FLATPAK_WRAPPER_BIN_DIR:-$HOME/.local/bin}"
MARKER="Generated by PenguinBurner Flatpak wrapper installer"
MODE="install"
FORCE=0
WRAPPERS=(
    penguin-burner
    pburn
    penguin-burner-ui
    pburn-ui
    penguin-burner-cli
    pburn-cli
    PENGUIN_BURNER
)

usage() {
    cat <<EOF
Usage: $0 [--force] [--uninstall] [--bin-dir DIR]

Install host PATH wrappers for the PenguinBurner Flatpak:
  penguin-burner, pburn, penguin-burner-ui, pburn-ui,
  penguin-burner-cli, pburn-cli, PENGUIN_BURNER

The wrappers forward to:
  flatpak run --command=<name> $APP_ID

Options:
  --force       overwrite existing non-PenguinBurner wrapper files
  --uninstall   remove wrappers previously created by this script
  --bin-dir DIR install/remove wrappers in DIR (default: $BIN_DIR)
EOF
}

die() {
    echo "error: $*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

is_managed_wrapper() {
    local path="$1"
    test -f "$path" && grep -Fq "$MARKER" "$path"
}

install_wrapper() {
    local command_name="$1"
    local target="$BIN_DIR/$command_name"

    if [[ -e "$target" && "$FORCE" != "1" ]] && ! is_managed_wrapper "$target"; then
        die "refusing to overwrite existing command: $target (rerun with --force)"
    fi

    cat >"$target" <<EOF
#!/usr/bin/env sh
# $MARKER
exec flatpak run --command=$command_name $APP_ID "\$@"
EOF
    chmod 755 "$target"
    echo "installed $target"
}

uninstall_wrapper() {
    local command_name="$1"
    local target="$BIN_DIR/$command_name"

    if [[ ! -e "$target" ]]; then
        return
    fi
    if ! is_managed_wrapper "$target"; then
        echo "skipped non-managed command: $target" >&2
        return
    fi
    rm -f "$target"
    echo "removed $target"
}

path_contains_bin_dir() {
    local entry
    IFS=: read -r -a path_entries <<<"${PATH:-}"
    for entry in "${path_entries[@]}"; do
        if [[ "$entry" == "$BIN_DIR" ]]; then
            return 0
        fi
    done
    return 1
}

while (($#)); do
    case "$1" in
        --force)
            FORCE=1
            ;;
        --uninstall)
            MODE="uninstall"
            ;;
        --bin-dir)
            shift
            [[ $# -gt 0 ]] || die "--bin-dir requires a directory"
            BIN_DIR="$1"
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
    shift
done

require_command flatpak

if [[ "$MODE" == "install" ]]; then
    flatpak info "$APP_ID" >/dev/null 2>&1 || die "Flatpak app is not installed: $APP_ID"
    mkdir -p "$BIN_DIR"
    for wrapper in "${WRAPPERS[@]}"; do
        install_wrapper "$wrapper"
    done
    if ! path_contains_bin_dir; then
        echo "warning: $BIN_DIR is not on PATH; add it to use pburn directly" >&2
    fi
else
    for wrapper in "${WRAPPERS[@]}"; do
        uninstall_wrapper "$wrapper"
    done
fi
